### ISSUE TITLE
mlc_chat_cli does not run on intel mac

### ISSUE THREAD

**Issue by hermannmolch** [mlc-ai/web-llm#101]
When starting mlc_chat_cli I get an error:

singerh$ mlc_chat_cli
Use lib /Users/singerh/dist/lib/vicuna-v1-7b-q3f16_0-metal.so
[10:01:38] /usr/local/miniconda/envs/mlc-llm-build/conda-bld/mlc-chat-nightly-package_1684213810850/work/cpp/cli_main.cc:298: model_path = /Users/singerh/dist/lib
[10:01:38] /Users/runner/work/utils/utils/tvm/src/runtime/dso_library.cc:125: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (lib_handle_ != nullptr) is false: Failed to load dynamic shared library /Users/singerh/dist/lib/vicuna-v1-7b-q3f16_0-metal.so dlopen(/Users/singerh/dist/lib/vicuna-v1-7b-q3f16_0-metal.so, 5): no suitable image found.  Did find:
	/Users/singerh/dist/lib/vicuna-v1-7b-q3f16_0-metal.so: mach-o, but wrong architecture
	/Users/singerh/dist/lib/vicuna-v1-7b-q3f16_0-metal.so: mach-o, but wrong architecture
Stack trace:
  [bt] (0) 1   libtvm_runtime.dylib                0x0000000106449db8 tvm::runtime::Backtrace() + 24
  [bt] (1) 2   libtvm_runtime.dylib                0x0000000106416a49 tvm::runtime::detail::LogFatal::Entry::Finalize() + 89
  [bt] (2) 3   libtvm_runtime.dylib                0x00000001064169e9 tvm::runtime::detail::LogFatal::~LogFatal() + 25
  [bt] (3) 4   libtvm_runtime.dylib                0x0000000106411279 tvm::runtime::detail::LogFatal::~LogFatal() + 9
  [bt] (4) 5   libtvm_runtime.dylib                0x0000000106437c4d tvm::runtime::DSOLibrary::Load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 269
  [bt] (5) 6   libtvm_runtime.dylib                0x0000000106437e4f tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::$_0> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) + 175
  [bt] (6) 7   libtvm_runtime.dylib                0x0000000106451ad6 tvm::runtime::Module::LoadFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 598
  [bt] (7) 8   mlc_chat_cli                        0x0000000105a8a5f7 main + 9287
  [bt] (8) 9   libdyld.dylib                       0x00007fff6e092cc9 start + 1

**Comment by tqchen** [comment]
closing as this issue belongs to mlc-llm
