### ISSUE TITLE
Canary decreased maxStorageBufferBindingSize limit?

### ISSUE THREAD

**Issue by DustinBrett** [mlc-ai/web-llm#119]
I am using Canary 116 and recently noticed my check for `maxStorageBufferBindingSize` being 1GB now fails and shows I only have 128MB's. This works fine on Chrome 113.

I tried removing that local check but then I get blocked by TVM with the message `Error: Cannot initialize runtime because of requested maxStorageBufferBindingSize exceeds limit. requested=1024MB, limit=128MB.`

Anyone else notice this or have an idea why?

**Comment by DustinBrett** [comment]
Although after uninstalling and reinstalling now it seems normal. Not sure what would cause that limit to go up and down but maybe this is a non-issue atm. That's part of the fun of using a canary version perhaps. :-)

**Comment by DustinBrett** [comment]
Actually I was wrong, it still fails in TVM, I had just removed my local checks so my testing was flawed. I tried to downgrade Canary but that is a fight I have so far lost. I am not sure if this is something that changed in Canary and I am not sure how to find out.

**Comment by tqchen** [comment]
Perhaps asking in dawn matrix channel might help

**Comment by DustinBrett** [comment]
> Perhaps asking in dawn matrix channel might help

Sure I will follow-up with that if this issue doesn't resolve itself. If anyone else using this project finds issues with Canary 116 then perhaps this issue can be expanded upon.

**Comment by DustinBrett** [comment]
I wonder if it's related to https://dawn-review.googlesource.com/c/dawn/+/130120

Hopefully it's resolved before a release. Does Web LLM work on latest Canary for others? For me it no longer works and complains about `maxStorageBufferBindingSize` being too small, which doesn't occur on Chrome 114.

**Comment by SamuelMarks** [comment]
Same issue occurs on Microsoft Edge Canary116.0.1908.0.

**Comment by SamuelMarks** [comment]
Same issue occurs on Microsoft Edge Canary 116.0.1908.0.

**Comment by DustinBrett** [comment]
As of 116.0.5833.0 this is now fixed in Canary. So I think it was indeed browser related.
