### ISSUE TITLE
document is not defined in Web Workers

### ISSUE THREAD

**Issue by DustinBrett** [mlc-ai/web-llm#124]
On [chat_module.ts#L44](https://github.com/mlc-ai/web-llm/blob/main/src/chat_module.ts#L44) & [chat_module.ts#L76](https://github.com/mlc-ai/web-llm/blob/main/src/chat_module.ts#L76) the usages of `document.URL` fail in Web Workers which don't have `document`. Perhaps instead this could be `globalThis.location.origin`.

A temp fix / test I'm doing in my worker is:

```js
globalThis.document = {
  URL: globalThis.location.origin,
};
```

If I use `globalThis.location.href` which is closer to `document.URL`, it can be a worker URL which likely isn't desired (and fails for me).

**Comment by tqchen** [comment]
Thanks @DustinBrett , do you mind to send a PR to fix this
