### ISSUE TITLE
Support for NextJs

### ISSUE THREAD

**Issue by narangkay** [mlc-ai/web-llm#126]
I had some trouble running this with next js (nothing major, some libraries not working out of the box). Would there be interest in me contributing code that I used to make it work?

You can see the changes needed to tvmjs here:
https://github.com/narangkay/mlc-ai-relax

and the changes to web-llm here:
https://github.com/narangkay/web-llm

**Comment by narangkay** [comment]
Sorry, I somehow missed your reply. My repo is kind of super out of date, and I had hacked super deep into the tvmjs repo to make things work. However, I tried using the freshest version of both web-llm and tvmjs, and was able to make it work with very minimal changes

1) "ignoreDynamicRequires: true," in common js plugin for rollup
2) A critical webpack config in the next project itself, which was super painful to figure out but seems to be working :)

```
webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback, // if you miss it, all the other options in fallback, specified
          // by next.js will be dropped. Doesn't make much sense, but how it is
        fs: false, // the solution
        module: false,
        perf_hooks: false,
      };
    }

    return config
  },
```

I sent over a PR for the issue, PTAL. Looking forward to retiring the clones of web-llm and tvmjs I had to create to make this work :)

**Comment by narangkay** [comment]
Thanks for the merge! What is the process for releasing to npm? I can volunteer to test the release in one of my apps to confirm it works :)

**Comment by tqchen** [comment]
Let me do a new release soon

**Comment by tqchen** [comment]
Just published a new release based on the latest change

**Comment by djaffer** [comment]
why did you close it. It still doesn't work. Spent a lot of time. If you build from source then production build fails.
