### ISSUE TITLE
WebLLM returns garbage on Chrome 114

### ISSUE THREAD

**Issue by hello-smile6** [mlc-ai/web-llm#130]
![image](https://github.com/mlc-ai/web-llm/assets/73048226/cbd102fe-0f03-446c-ae89-dc042e6405f9)
I've tried several times, and it only ever returns random text.

**Comment by tqchen** [comment]
interesting, i double checked with 114 and it seems to be fine. Can you try to 
goto https://webgpureport.org/ and check the gpu setting

Try a different kind of model


Wonder if it is related to the GPU that you are using

**Comment by yzh119** [comment]
The quantized RedPajama model is not good at replying to greetings such "hello." (and Vicuna is much better).
If you ask RedPajama to help generate some stories, the reply is much better.

**Comment by tqchen** [comment]
closing for now as there is no actionable item atm, feel free to open new ones
