### ISSUE TITLE
Error Not Working QuotaExceededError: Failed to execute 'add' on 'Cache': Quota exceeded.

### ISSUE THREAD

**Issue by putuoka** [mlc-ai/web-llm#144]
<img width="683" alt="image" src="https://github.com/mlc-ai/web-llm/assets/20880839/b7ad7239-0583-4374-a246-39e090eb591f">

**Comment by MasterJH5574** [comment]
Hi @putuoka, do you run in Incognito mode? Incognito has tighter limitation and is likely not gonna work. You can try run without Incognito mode if so.

**Comment by putuoka** [comment]
> Hi @putuoka, do you run in Incognito mode? Incognito has tighter limitation and is likely not gonna work. You can try run without Incognito mode if so.

Thanks for the quick reply! yeah I always use incognito mode cuz there's a lot of bad people out there. I'll try running without Incognito mode and see if that fixes the issue.

**Comment by DavidGOrtega** [comment]
I have this error with or without incognito mode. This is a pretty strong bug right now.

 - [ ] Chrome 121.0.6167.85 MacBook Pro M1 MACOS Ventura 13.6.3

**Comment by CharlieFRuan** [comment]
Update: both Cache API and IndexedDB cache are supported now in `0.2.31`. User can choose either with `AppConfig.useIndexedDBCache`. Try to use either to see if the issue exists in both.

For more see the PR:
- https://github.com/mlc-ai/web-llm/pull/352

We also exposed some cache-related utils (e.g. deleting the model (either weights or wasm) from cache, checking if a model exists in cache). See its usage in `examples/cache-usage`.

**Comment by DavidGOrtega** [comment]
this issue should be closed then @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Closing this as of now, feel free to open new ones if issues persist.

**Comment by talperetz** [comment]
👋🏽  @CharlieFRuan, I get this quota error too. When trying with `useIndexedDBCache = true` I get
`Uncaught Error: ArtifactIndexedDBCache failed to fetch: https://huggingface.co/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/resolve/main/params_shard_2.bin` with all models.

This is currently a blocker for me to use the package.

**Comment by CharlieFRuan** [comment]
@talperetz To triage a bit, when not using indexedDB, does it work? And which browser are you using, is it Chrome? Could you show the console, perhaps both Network and Application-storage. Thanks!

**Comment by talperetz** [comment]
I'm using chrome `125.0.6422.142`
I'm using the webgpu chrome extension example with `useIndexedDBCache = true` (without it it fails to load, errors with QuotaExceededError: Failed to execute 'add' on 'Cache': Quota exceeded)
![CleanShot 2024-06-02 at 15 11 34@2x](https://github.com/mlc-ai/web-llm/assets/11588598/10840e5b-bcdb-456b-a1a5-7ae3d7eddd57)

**Comment by talperetz** [comment]
I'm using chrome 125.0.6422.142
I'm using the webgpu chrome extension example with useIndexedDBCache = true (without it it fails to load, errors with QuotaExceededError: Failed to execute 'add' on 'Cache': Quota exceeded)

This is the service worker network:

![CleanShot 2024-06-02 at 15 16 19@2x](https://github.com/mlc-ai/web-llm/assets/11588598/5199d837-bb90-491a-9ceb-0387604747c1)

console is empty, storage seems empty too.

**Comment by DavidGOrtega** [comment]
@talperetz I write why this is happening [here](https://github.com/mlc-ai/web-llm/issues/374). Its Chrome issue in MacOS but might happen in other OS

**Comment by talperetz** [comment]
Thanks @DavidGOrtega that's exactly the issue I'm seeing. Confirmed that changing the chrome settings works.
