### ISSUE TITLE
Can I try this with other LLMs (for example manticore-13b?)

### ISSUE THREAD

**Issue by salamanders** [mlc-ai/web-llm#147]
Absolutely mind-blowing that this works in a browser.  Love it!  Can other LLMs be converted into something that this can draw from?  (like manticore-13b?)

**Comment by tqchen** [comment]
Thanks @salamanders , we are in the progress of adding more docs and enable generalization, you can check out current docs at https://mlc.ai/mlc-llm/docs/ likely it will be supported out of box, however, we are still in the process of getting default out of box perf, which will land soonish, and then all llama variants can be used
