### ISSUE TITLE
Mismatched and missing conversation templates between `web-llm` and `mlc_llm`

### ISSUE THREAD

**Issue by jparismorgan** [mlc-ai/web-llm#150]
### What
There are a few conversation templates which `mlc_llm` has but `web-llm` doesn't, specifically it seems like all of these: `llama_default`, `conv_one_shot`, `rwkv`, `gorilla`, `guanaco`, `dolly`, `oasst`, `stablelm`, `minigpt`, `moss`, `LM`, `code_gpt`:

<img width="1865" alt="Screenshot 2023-07-13 at 10 37 14 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/f00bab73-2970-4991-9111-725e21f5e5d4">

Assuming I'm reading this correctly and we should actually have a match for each, it seems nice to add versions of these templates to `web-llm`. Specifically I am most interested in the separator for `gptj`.

I did considering adding it myself, but I don't quite understand how to map between them. I.e. here is what we have currently:
| model | `web-llm`  | `mlc_llm` |
| ------------- | ------------- | ------------- |
| wizardlm | <img width="687" alt="Screenshot 2023-07-13 at 10 44 29 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/9c331268-d374-4149-a9bf-08c90583430b">  |  <img width="515" alt="Screenshot 2023-07-13 at 10 41 00 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/dc808338-0bee-4507-844a-b9d315dd6e4b"> |
| redpajama_chat | <img width="410" alt="Screenshot 2023-07-13 at 10 42 13 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/e2d07136-ca6a-41ad-8bf9-3530ec9f675e"> | <img width="409" alt="Screenshot 2023-07-13 at 10 42 29 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/6c5dbb16-52b0-490a-b5aa-9a87b8759fe9"> |
| vicuna_v1.1  | <img width="680" alt="Screenshot 2023-07-13 at 10 43 16 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/13f02db2-4175-4a44-be15-351c1f1bc5bd"> | <img width="689" alt="Screenshot 2023-07-13 at 10 43 08 AM" src="https://github.com/mlc-ai/web-llm/assets/1396242/2b36c4b8-20e7-4629-b89d-5b3f1f9dc52a">

So, my specific questions:
* Should there be a 1-1 mapping here?
* Which field takes precedent if they differ?
* Should all fields that are shared be the same? I.e. is there supposed to be a difference in the `roles` or `seps` fields? 
* Assuming everything should match, is there a way to just use the `cpp/conv_templates.cc` version of this data so that things can't get out of sync in the future?

Thank you for any help!

**Comment by nayarahilton** [comment]
+1 Init error, Error: Unknown conv template `codellama_instruct`

**Comment by tqchen** [comment]
this is now fixed and all convo templates are standardized
