### ISSUE TITLE
8GB GPU

### ISSUE THREAD

**Issue by zwilch** [mlc-ai/web-llm#161]
vicuna model: After some Input Text and some generated questions, the GPU VRAM (win10 taskmanager) goes up to fill 8GB and then token generation become slow. 
but direcly after start it is really fast, is there somethin missing to free memory after each answhere?

**Comment by CharlieFRuan** [comment]
Closing this issue for now due to staleness. Try smaller models (e.g. Phi3.5, Qwen2) and see if the same problem is observed. Feel free to re-open new issues as well.
