### ISSUE TITLE
The operation failed for an operation-specific reason

### ISSUE THREAD

**Issue by TechGeekUnited** [mlc-ai/web-llm#170]
I Had the same [issue with WEBSD](https://github.com/mlc-ai/web-stable-diffusion/issues/48) when i switched to canary WEBsd Worked but WEBllm still gives the error frequently(Image attached)
![Screenshot 2023-08-04 144404](https://github.com/mlc-ai/web-llm/assets/79381496/cd6cf817-16f4-4a2b-84b9-6b4f132636e3)

**Comment by patnorris** [comment]
While the smaller model (RedPajama-INCITE-Chat-3B-v1-q4f32_0) has been working smoothly for me, I'm observing similar errors as reported for Llama-2-7b-chat-hf-q4f32_1. I also tried vicuna-v1-7b-q4f32_0 which worked fine for a message or two until I opened another browser tab (the screen went black and then got "GPU connection lost", "OperationError: The operation failed for an operation-specific reason" and "DOMException: Device is lost") which makes me think that maybe my device cannot handle the needed memory for WebGPU that these bigger models demand. From some initial research about the errors, I also found comments that the browser throws them when it cannot allocate enough memory to WebGPU. Could this be the reason? Do you know of any potential way this could be solved?
