### ISSUE TITLE
Build web-llm from sourcecode fail

### ISSUE THREAD

**Issue by burke-up** [mlc-ai/web-llm#171]
here is what i do: [https://colab.research.google.com/drive/1uHvSg0Cy5-iwfa_VIMV_e1DGtRTjdvSO?usp=sharing](https://colab.research.google.com/drive/1uHvSg0Cy5-iwfa_VIMV_e1DGtRTjdvSO?usp=sharing)
when run the cmd :

`!cd web-llm && ./scripts/prep_deps.sh`
i got the output, which  contains error

+ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.44 (bec42dac7873903d09d713963e34020c22a8bd2d)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ npm --version
6.14.8
+ TVM_HOME_SET=
+ [[ -z '' ]]
+ [[ ! -d 3rdparty/tvm-unity ]]
+ echo 'Do not find TVM_HOME env variable, cloning a version as source.'
Do not find TVM_HOME env variable, cloning a version as source.
+ git clone https://github.com/mlc-ai/relax 3rdparty/tvm-unity --recursive
Cloning into '3rdparty/tvm-unity'...
remote: Enumerating objects: 187825, done.
remote: Counting objects: 100% (12495/12495), done.
remote: Compressing objects: 100% (1770/1770), done.
remote: Total 187825 (delta 10850), reused 11959 (delta 10620), pack-reused 175330
Receiving objects: 100% (187825/187825), 70.07 MiB | 16.82 MiB/s, done.
Resolving deltas: 100% (146352/146352), done.
Submodule '3rdparty/OpenCL-Headers' (https://github.com/KhronosGroup/OpenCL-Headers.git) registered for path '3rdparty/OpenCL-Headers'
Submodule '3rdparty/cnpy' (https://github.com/rogersce/cnpy.git) registered for path '3rdparty/cnpy'
Submodule '3rdparty/cutlass' (https://github.com/NVIDIA/cutlass.git) registered for path '3rdparty/cutlass'
Submodule '3rdparty/cutlass_fpA_intB_gemm' (https://github.com/tlc-pack/cutlass_fpA_intB_gemm) registered for path '3rdparty/cutlass_fpA_intB_gemm'
Submodule 'dlpack' (https://github.com/dmlc/dlpack.git) registered for path '3rdparty/dlpack'
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core.git) registered for path '3rdparty/dmlc-core'
Submodule '3rdparty/libbacktrace' (https://github.com/tlc-pack/libbacktrace.git) registered for path '3rdparty/libbacktrace'
Submodule '3rdparty/libflash_attn' (https://github.com/tlc-pack/libflash_attn) registered for path '3rdparty/libflash_attn'
Submodule '3rdparty/rang' (https://github.com/agauniyal/rang.git) registered for path '3rdparty/rang'
Submodule '3rdparty/vta-hw' (https://github.com/apache/tvm-vta.git) registered for path '3rdparty/vta-hw'
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/OpenCL-Headers'...
remote: Enumerating objects: 1276, done.        
remote: Counting objects: 100% (299/299), done.        
remote: Compressing objects: 100% (122/122), done.        
remote: Total 1276 (delta 244), reused 196 (delta 174), pack-reused 977        
Receiving objects: 100% (1276/1276), 742.54 KiB | 14.56 MiB/s, done.
Resolving deltas: 100% (828/828), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/cnpy'...
remote: Enumerating objects: 164, done.        
remote: Total 164 (delta 0), reused 0 (delta 0), pack-reused 164        
Receiving objects: 100% (164/164), 52.32 KiB | 3.27 MiB/s, done.
Resolving deltas: 100% (94/94), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/cutlass'...
remote: Enumerating objects: 21527, done.        
remote: Counting objects: 100% (5667/5667), done.        
remote: Compressing objects: 100% (787/787), done.        
remote: Total 21527 (delta 5056), reused 5015 (delta 4867), pack-reused 15860        
Receiving objects: 100% (21527/21527), 31.64 MiB | 26.87 MiB/s, done.
Resolving deltas: 100% (15873/15873), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/cutlass_fpA_intB_gemm'...
remote: Enumerating objects: 292, done.        
remote: Counting objects: 100% (292/292), done.        
remote: Compressing objects: 100% (122/122), done.        
remote: Total 292 (delta 170), reused 270 (delta 151), pack-reused 0        
Receiving objects: 100% (292/292), 129.28 KiB | 6.80 MiB/s, done.
Resolving deltas: 100% (170/170), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack'...
remote: Enumerating objects: 462, done.        
remote: Counting objects: 100% (99/99), done.        
remote: Compressing objects: 100% (42/42), done.        
remote: Total 462 (delta 72), reused 67 (delta 57), pack-reused 363        
Receiving objects: 100% (462/462), 1.70 MiB | 17.46 MiB/s, done.
Resolving deltas: 100% (160/160), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core'...
remote: Enumerating objects: 6334, done.        
remote: Counting objects: 100% (198/198), done.        
remote: Compressing objects: 100% (140/140), done.        
remote: Total 6334 (delta 87), reused 109 (delta 37), pack-reused 6136        
Receiving objects: 100% (6334/6334), 1.71 MiB | 17.82 MiB/s, done.
Resolving deltas: 100% (3833/3833), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/libbacktrace'...
remote: Enumerating objects: 459, done.        
remote: Counting objects: 100% (311/311), done.        
remote: Compressing objects: 100% (36/36), done.        
remote: Total 459 (delta 285), reused 275 (delta 275), pack-reused 148        
Receiving objects: 100% (459/459), 1.03 MiB | 12.90 MiB/s, done.
Resolving deltas: 100% (341/341), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/libflash_attn'...
remote: Enumerating objects: 112, done.        
remote: Counting objects: 100% (112/112), done.        
remote: Compressing objects: 100% (40/40), done.        
remote: Total 112 (delta 70), reused 112 (delta 70), pack-reused 0        
Receiving objects: 100% (112/112), 35.79 KiB | 2.39 MiB/s, done.
Resolving deltas: 100% (70/70), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/rang'...
remote: Enumerating objects: 735, done.        
remote: Counting objects: 100% (31/31), done.        
remote: Compressing objects: 100% (27/27), done.        
remote: Total 735 (delta 9), reused 15 (delta 3), pack-reused 704        
Receiving objects: 100% (735/735), 265.43 KiB | 6.03 MiB/s, done.
Resolving deltas: 100% (371/371), done.
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/vta-hw'...
remote: Enumerating objects: 3312, done.        
remote: Counting objects: 100% (330/330), done.        
remote: Compressing objects: 100% (137/137), done.        
remote: Total 3312 (delta 258), reused 193 (delta 193), pack-reused 2982        
Receiving objects: 100% (3312/3312), 1.43 MiB | 13.31 MiB/s, done.
Resolving deltas: 100% (1442/1442), done.
Submodule path '3rdparty/OpenCL-Headers': checked out 'b590a6bfe034ea3a418b7b523e3490956bcb367a'
Submodule path '3rdparty/cnpy': checked out '4e8810b1a8637695171ed346ce68f6984e585ef4'
Submodule path '3rdparty/cutlass': checked out '146d314057c5f193a70c2b36896e739c8c60aef4'
Submodule path '3rdparty/cutlass_fpA_intB_gemm': checked out '390e821fbad2356089aab603d7116c6c820eae65'
Submodule 'cutlass' (https://github.com/NVIDIA/cutlass) registered for path '3rdparty/cutlass_fpA_intB_gemm/cutlass'
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/cutlass_fpA_intB_gemm/cutlass'...
remote: Enumerating objects: 21527, done.        
remote: Counting objects: 100% (5610/5610), done.        
remote: Compressing objects: 100% (775/775), done.        
remote: Total 21527 (delta 4996), reused 4978 (delta 4822), pack-reused 15917        
Receiving objects: 100% (21527/21527), 31.56 MiB | 25.67 MiB/s, done.
Resolving deltas: 100% (15874/15874), done.
Submodule path '3rdparty/cutlass_fpA_intB_gemm/cutlass': checked out 'cc85b64cf676c45f98a17e3a47c0aafcf817f088'
Submodule path '3rdparty/dlpack': checked out 'e2bdd3bee8cb6501558042633fa59144cc8b7f5f'
Submodule path '3rdparty/dmlc-core': checked out '09511cf9fe5ff103900a5eafb50870dc84cc17c8'
Submodule path '3rdparty/libbacktrace': checked out '08f7c7e69f8ea61a0c4151359bc8023be8e9217b'
Submodule path '3rdparty/libflash_attn': checked out '58b343e57571fe5e0a5b43b5eb721acef8b35dff'
Submodule 'cutlass' (https://github.com/NVIDIA/cutlass/) registered for path '3rdparty/libflash_attn/cutlass'
Cloning into '/content/web-llm/3rdparty/tvm-unity/3rdparty/libflash_attn/cutlass'...
remote: Enumerating objects: 21527, done.        
remote: Counting objects: 100% (5667/5667), done.        
remote: Compressing objects: 100% (787/787), done.        
remote: Total 21527 (delta 5056), reused 5015 (delta 4867), pack-reused 15860        
Receiving objects: 100% (21527/21527), 31.64 MiB | 25.10 MiB/s, done.
Resolving deltas: 100% (15873/15873), done.
Submodule path '3rdparty/libflash_attn/cutlass': checked out 'c4f6b8c6bc94ff69048492fb34df0dfaf1983933'
Submodule path '3rdparty/rang': checked out 'cabe04d6d6b05356fa8f9741704924788f0dd762'
Submodule path '3rdparty/vta-hw': checked out '36a91576edf633479c78649e050f18dd2ddc8103'
+ export TVM_HOME=3rdparty/tvm-unity
+ TVM_HOME=3rdparty/tvm-unity
+ cd 3rdparty/tvm-unity/web
+ make
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -c -MM -MT dist/wasm/wasm_runtime.bc emcc/wasm_runtime.cc >dist/wasm/wasm_runtime.d
shared:INFO: (Emscripten: Running sanity checks)
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -emit-llvm -c -o dist/wasm/wasm_runtime.bc emcc/wasm_runtime.cc
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -c -MM -MT dist/wasm/tvmjs_support.bc emcc/tvmjs_support.cc >dist/wasm/tvmjs_support.d
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -emit-llvm -c -o dist/wasm/tvmjs_support.bc emcc/tvmjs_support.cc
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -c -MM -MT dist/wasm/webgpu_runtime.bc emcc/webgpu_runtime.cc >dist/wasm/webgpu_runtime.d
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -emit-llvm -c -o dist/wasm/webgpu_runtime.bc emcc/webgpu_runtime.cc
emcc -I/content/web-llm/3rdparty/tvm-unity -I/content/web-llm/3rdparty/tvm-unity/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/content/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/content/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -o dist/wasm/tvmjs_runtime.js dist/wasm/wasm_runtime.bc dist/wasm/tvmjs_support.bc dist/wasm/webgpu_runtime.bc --no-entry -s WASM_BIGINT=1 -s ALLOW_MEMORY_GROWTH=1 -s STANDALONE_WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 --pre-js emcc/preload.js
cache:INFO: generating system asset: symbol_lists/86aab5bd1073bc9aeaa89e6e9e5c919e2ffae24c.json... (this will be cached in "/content/emsdk/upstream/emscripten/cache/symbol_lists/86aab5bd1073bc9aeaa89e6e9e5c919e2ffae24c.json" for subsequent builds)
cache:INFO:  - ok
warning: undefined symbol: TVMWasmPackedCFunc (referenced by root reference (e.g. compiled C/C++ code))
warning: undefined symbol: TVMWasmPackedCFuncFinalizer (referenced by root reference (e.g. compiled C/C++ code))
warning: undefined symbol: _ZN3tvm7runtime9threading10NumThreadsEv (referenced by root reference (e.g. compiled C/C++ code))
warning: undefined symbol: _ZN3tvm7runtime9threading15ResetThreadPoolEv (referenced by root reference (e.g. compiled C/C++ code))
emcc: warning: warnings in JS library compilation [-Wjs-compiler]
python3 emcc/decorate_as_wasi.py dist/wasm/tvmjs_runtime.js dist/wasm/tvmjs_runtime.wasi.js cjs
python3 emcc/decorate_as_wasi.py dist/wasm/tvmjs_runtime.js src/tvmjs_runtime_wasi.js es
+ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN notsup Unsupported engine for @typescript-eslint/eslint-plugin@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@5.62.0
npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.62.0
npm WARN notsup Unsupported engine for eslint@8.46.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: eslint@8.46.0
npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@5.62.0
npm WARN notsup Unsupported engine for @typescript-eslint/type-utils@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/type-utils@5.62.0
npm WARN notsup Unsupported engine for @typescript-eslint/utils@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/utils@5.62.0
npm WARN notsup Unsupported engine for @typescript-eslint/types@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/types@5.62.0
npm WARN notsup Unsupported engine for @typescript-eslint/visitor-keys@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/visitor-keys@5.62.0
npm WARN notsup Unsupported engine for eslint-visitor-keys@3.4.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: eslint-visitor-keys@3.4.2
npm WARN notsup Unsupported engine for @typescript-eslint/typescript-estree@5.62.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/typescript-estree@5.62.0
npm WARN notsup Unsupported engine for @eslint-community/eslint-utils@4.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @eslint-community/eslint-utils@4.4.0
npm WARN notsup Unsupported engine for @eslint/eslintrc@2.1.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @eslint/eslintrc@2.1.1
npm WARN notsup Unsupported engine for @eslint/js@8.46.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @eslint/js@8.46.0
npm WARN notsup Unsupported engine for eslint-scope@7.2.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: eslint-scope@7.2.2
npm WARN notsup Unsupported engine for espree@9.6.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: espree@9.6.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for minimatch@9.0.3: wanted: {"node":">=16 || 14 >=14.17"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: minimatch@9.0.3
npm WARN tvmjs@0.14.0-dev0 No repository field.

added 632 packages from 363 contributors and audited 635 packages in 20.413s

62 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

+ npm run build

> tvmjs@0.14.0-dev0 build /content/web-llm/3rdparty/tvm-unity/web
> rollup -c

src/index.ts → lib/index.js...
[!] (plugin rpt2) Error: src/webgpu.ts:161:5 - error TS2322: Type 'RenderingContext' is not assignable to type 'GPUCanvasContext'.
  Type 'CanvasRenderingContext2D' is missing the following properties from type 'GPUCanvasContext': __brand, configure, unconfigure, getCurrentTexture

161     this.canvasContext = ctx;
        ~~~~~~~~~~~~~~~~~~

src/index.ts

    at error (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup/dist/shared/rollup.js:21718:12)
    at Object.error (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup/dist/shared/rollup.js:22672:20)
    at RollupContext.error (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup-plugin-typescript2/src/context.ts:35:17)
    at /content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup-plugin-typescript2/src/diagnostics.ts:70:17
    at Array.forEach (<anonymous>)
    at printDiagnostics (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup-plugin-typescript2/src/diagnostics.ts:42:14)
    at typecheckFile (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup-plugin-typescript2/src/index.ts:67:3)
    at Object.<anonymous> (/content/web-llm/3rdparty/tvm-unity/web/node_modules/rollup-plugin-typescript2/src/index.ts:257:5)
    at Generator.next (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tvmjs@0.14.0-dev0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tvmjs@0.14.0-dev0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-10T07_29_41_634Z-debug.log
+ rm -rf tvm_home
+ ln -s 3rdparty/tvm-unity tvm_home
+ npm install
npm WARN tvmjs@0.14.0-dev0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 635 packages in 4.056s

62 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

+ cd examples/simple-chat
./scripts/prep_deps.sh: line 22: cd: examples/simple-chat: No such file or directory


how to fix the bug

**Comment by QFleet** [comment]
i have the same issue. i think that is the mismatch version of 3rdparty/tvm-unity.
my issue detail:
```
src/index.ts → lib/index.js...
[!] (plugin rpt2) Error: src/webgpu.ts:161:5 - error TS2322: Type 'RenderingContext' is not assignable to type 'GPUCanvasContext'.
  Type 'CanvasRenderingContext2D' is missing the following properties from type 'GPUCanvasContext': __brand, configure, unconfigure, getPreferredFormat, getCurrentTexture

161     this.canvasContext = ctx;
```

you can have a try as below:
`this.canvasContext = ctx as any;`

**Comment by burke-up** [comment]
> i have the same issue. i think that is the mismatch version of 3rdparty/tvm-unity. my issue detail:
> 
> ```
> src/index.ts → lib/index.js...
> [!] (plugin rpt2) Error: src/webgpu.ts:161:5 - error TS2322: Type 'RenderingContext' is not assignable to type 'GPUCanvasContext'.
>   Type 'CanvasRenderingContext2D' is missing the following properties from type 'GPUCanvasContext': __brand, configure, unconfigure, getPreferredFormat, getCurrentTexture
> 
> 161     this.canvasContext = ctx;
> ```
> 
> you can have a try as below: `this.canvasContext = ctx as any;` // edited in 3rdparty/tvm-unity/web/src/webgpu.ts line#161


Your response has been very helpful to me and has helped me solve the problem.

**Comment by MasterJH5574** [comment]
Thanks @QFleet and @burke-up! The issue is now fixed at https://github.com/apache/tvm/commit/a66e1cd1f58c8744f1718b7535f5fcce53f75557
