### ISSUE TITLE
How do I support multiple GPU in the laptop or choose GPU 1 if the system have 2 ?

### ISSUE THREAD

**Issue by raymond-infinitecode** [mlc-ai/web-llm#192]
There is a laptop with Intel GPU as GPU 0 and Nvidia T600 as GPU 1,
Is it possible for us to tweak the settings to point to a faster Nvidia T600 GPU?
is the configuration done via Chrome or the WEBLLM?

**Comment by zwilch** [comment]
I found something with google like that: 
https://pureinfotech.com/set-gpu-app-windows-10/
you can set the GPU to an APP for example chrome app should use a specific gpu

**Comment by zwilch** [comment]
> webgpu only support single gpu for now,and likely will choose the best default i think

on windows it choose the GPU wich you have assigned to the app "chrome"
see => https://pureinfotech.com/set-gpu-app-windows-10/
