### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by curran** [mlc-ai/web-llm#196]
I load the demo page and enter "test", then this is what I see:

![image](https://github.com/mlc-ai/web-llm/assets/68416/77f9ccdf-a148-42e7-a1e6-9e694d099b3f)

at https://webllm.mlc.ai/#chat-demo

**Comment by CharlieFRuan** [comment]
Hi, we'd recommend using the latest version of Chrome. Before trying the demo, you can also go to webgpureport.org to see the availability of WebGPU.
