### ISSUE TITLE
LinkError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by yobi213** [mlc-ai/web-llm#198]
I encountered an error after compiling a WebAssembly (Wasm) format using mlc-llm. The error message I received is as follows:

Init error, LinkError: WebAssembly.instantiate(): Import #2 module="env" function="_ZN3tvm7runtime15NVTXScopedRangeD1Ev" error: function import requires a callable

I've uploaded the compilation artifacts to the following locations:

Hugging Face Model Hub: [Link](https://huggingface.co/yobi/RedPajama-INCITE-Chat-3B-v1-q4f32_1)
GitHub Repository: [Link](https://github.com/yobi213/webgpu-practice/blob/main/RedPajama-INCITE-Chat-3B-v1-q4f32_1-webgpu.wasm)

The webllm npm server does not load when using the wasm file provided in my GitHub. However, when I replace only the wasm file with the wasm from mlc-ai repository and keep the rest of the Hugging Face model, the server can load the model. Here is the replacement wasm file link:

[Replacement WebAssembly File](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/RedPajama-INCITE-Chat-3B-v1-q4f32_1-webgpu.wasm)

I'm wondering if this issue might be related to the version of emcc or my environment. I'm using a MacBook with a silicon chip.

**Comment by felladrin** [comment]
I'm facing the same issue when building the .wasm on an Apple Silicon chip.

**Comment by felladrin** [comment]
It seems the issue started happening after this commit on the Relax repo: https://github.com/mlc-ai/relax/commit/6d085ae6f019abfd7da68419a0237cd5ee043b01

After that commit, running `make web` displays the warnings:
```
warning: undefined symbol: _ZN3tvm7runtime15NVTXScopedRangeC2EPKc (referenced by root reference (e.g. compiled C/C++ code))
warning: undefined symbol: _ZN3tvm7runtime15NVTXScopedRangeD1Ev (referenced by root reference (e.g. compiled C/C++ code))
warning: undefined symbol: _ZN3tvm7runtime9threading10NumThreadsEv (referenced by root reference (e.g. compiled C/C++ code))
warning: undefined symbol: _ZN3tvm7runtime9threading15ResetThreadPoolEv (referenced by root reference (e.g. compiled C/C++ code))
```

**Comment by taishi55** [comment]
I'm getting the related error
`
Uncaught (in promise) CompileError: WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because neither 'wasm-eval' nor 'unsafe-eval' is an allowed source of script in the following Content Security Policy directive: "script-src 'self'"
`
