### ISSUE TITLE
Mistral-7B support

### ISSUE THREAD

**Issue by avaer** [mlc-ai/web-llm#202]
Mistral-7B is a high quality open model (Apache 2.0).

It seems like it would be a perfect candidate for support in WebLLM.

https://huggingface.co/mistralai/Mistral-7B-v0.1
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1

**Comment by felladrin** [comment]
Got [Mistral-7B-OpenOrca](https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca) working, but with one caveat: sometimes, it doesn't stop the inference. After it prints `<|im_end|>` (OpenOrca uses ChatML), it starts outputting an empty string. A workaround is to capture the output inside the `generateProgressCallback` and interrupt the generation if the output is an empty string:

```javascript
let lastResponse = "";

const generateProgressCallback = (_, message = "") => {
  if (message.length === 0) return chat.interruptGenerate();

  lastResponse = message;

  console.log(`Partial response: ${lastResponse}`);
};

const prompt = "Please tell me how mistral winds have attracted super-orcas.";

await chat.generate(prompt, generateProgressCallback);

console.log(`Complete response: ${lastResponse}`);
```

You can find the Mistral 7B OpenOrca web-llm build here:
https://huggingface.co/Felladrin/mlc-chat-Mistral-7B-OpenOrca-q4f32_1

And here's a demo:
https://huggingface.co/spaces/Felladrin/Web-LLM-Mistral-7B-OpenOrca

**Comment by avaer** [comment]
Awesome!!

Would this same code be compatible with untuned Mistral-7B with a `webgpu` quantization as specified here: https://llm.mlc.ai/docs/compilation/compile_models.html ?

**Comment by felladrin** [comment]
It's compatible! I've compiled and uploaded both to HuggingFace:
- https://huggingface.co/Felladrin/mlc-chat-Mistral-7B-v0.1-q4f32_1
- https://huggingface.co/Felladrin/mlc-chat-Mistral-7B-Instruct-v0.1-q4f32_1

**Comment by sam1am** [comment]
> It's compatible! I've compiled and uploaded both to HuggingFace:
> - https://huggingface.co/Felladrin/mlc-chat-Mistral-7B-v0.1-q4f32_1
> - https://huggingface.co/Felladrin/mlc-chat-Mistral-7B-Instruct-v0.1-q4f32_1

I get "download model config failed" when I try to add either of these in mlc.

**Comment by felladrin** [comment]
> I get "download model config failed" when I try to add either of these in mlc.

Hey, @sam1am, 
I guess you're trying to run the model in an incompatible compilation target.
It's currently built to run only on browsers (target: webgpu).
Making it run on other MLC targets requires compiling it accordingly, but it's out of the scope of this repo.
Just in case, I've updated my previous comment to clarify it.

**Comment by hrishioa** [comment]
@felladrin did you use any specific compilation config to get the output? Your wasm works, but I'm trying to compile with `python3 -m mlc_llm.build --hf-path <mistral_model> --target webgpu --quantization q4f32_1` and keep getting `Init error, LinkError: WebAssembly.instantiate(): Import #2 module="env" function="_ZN3tvm7runtime15NVTXScopedRangeD1Ev": function import requires a callable` with my wasm files. I've tried compiling from CUDA 11.8 and Apple M1.

**Comment by felladrin** [comment]
Oh yeah. Been through [that same problem](https://github.com/mlc-ai/web-llm/issues/198#issuecomment-1751821829), @hrishioa. And indeed I had to change one thing: the version of the TVM git submodule.
For this, after cloning https://github.com/mlc-ai/mlc-llm, go into `3rdparty/tvm` folder and run:
```bash
git checkout 5828f1e9e \
  && git submodule init \
  && git submodule update --recursive \
  && make webclean \
  && make web
```

**Comment by hrishioa** [comment]
Thank you! That fixed that issue, but I'm now running into this with relax:

```
InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc vm.builtin.attention_kv_cache_window_override in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
```

Is this because of the tvm version?

**Comment by felladrin** [comment]
Haven't seen that one, @hrishioa. Maybe something they changed recently on `mlc-llm` repo.
I haven't updated the repo since I built mistral, so maybe if you checkout the same version it could work...

> git checkout 1e6fb11658356b1c394871872d480eef9f2c9197

<details>
<summary>Should put the repo in this commit:</summary>
<img width="457" alt="image" src="https://github.com/mlc-ai/web-llm/assets/418083/eb90d30a-b5ea-4f9a-84a0-746faf84631b">
</details>

Remember to reinitialize all the git submodules and also re-checkout `3rdparty/tvm` submodule to `5828f1e9e`.

Ah, if you're building to `f32`, there was one more edit needed (it seems [they fixed it already](https://github.com/mlc-ai/mlc-llm/pull/1078), but in that old commit, it wasn't fixed yet):
```bash
sed -i '.bak' 's/float16/float32/g' mlc_llm/transform/fuse_split_rotary_embedding.py
```

**Comment by hrishioa** [comment]
@felladrin Thank you! That worked. Pulling the main repo to `1e6fb`, relax to `5828f1` and rebuilding helped fix that problem.

Updating float16 to float32 fixed compiling 32 bit formats, but 16's are now failing - that's something I can live with :)

Couple more things in case anyone's on this thread:
1. The appropriate value for `conv_template` seems to be `custom`, but it's not released yet I think.
2. Are `sliding_window` and `sliding_window_chunk_size` working? I can see they're merged into mlc-llm [here](https://github.com/mlc-ai/mlc-llm/pull/1087/commits/77889c778499fde95d153f493ab390065d60d611) but I don't see any mention in web-llm. Is it worth having them in `mlc-chat-config.json`? I didn't notice a difference in inference quality or speed.
3. Compiling [Yarn-Mistral-128K](https://huggingface.co/NousResearch/Yarn-Mistral-7b-128k) pulls emcc out of memory. Had to edit the compiler options in `3rdparty/tvm/../emcc.py` to add these:
```python
cmd += ["-s", "INITIAL_MEMORY=1342177280"]
cmd += ["-s", "TOTAL_MEMORY=1342177280"]
```

This gets compilation to finish, but I end up with this error. Any ideas?

**Comment by felladrin** [comment]
Glad it worked!

> 1. The appropriate value for conv_template seems to be custom, but it's not released yet I think.
> 2. Are sliding_window and sliding_window_chunk_size working? I can see they're merged into mlc-llm [here](https://github.com/mlc-ai/mlc-llm/pull/1087/commits/77889c778499fde95d153f493ab390065d60d611) but I don't see any mention in web-llm. Is it worth having them in mlc-chat-config.json? I didn't notice a difference in inference quality or speed.
> 3. Compiling [Yarn-Mistral-128K](https://huggingface.co/NousResearch/Yarn-Mistral-7b-128k) pulls emcc out of memory.

About `1`: you can use [any of the available `conv_template`](https://github.com/mlc-ai/web-llm/blob/72f1e42ed6f78adf6d63c15b937a020e07c76759/src/conversation.ts#L114C1-L114C1) and completely override the params directly in `mlc-chat-config.json`, like it was done [here](https://huggingface.co/Felladrin/mlc-chat-Mistral-7B-OpenOrca-q4f32_1/blob/8b331fd08fc3f7c73eae446b93b07a1ada0e8dd4/params/mlc-chat-config.json#L4-L10).

I'm afraid I won't be able to help with `2` and `3`.

**Comment by hrishioa** [comment]
Thanks for all the help!

Compiled and ran OpenHermes-2.5 and Dolphin 2.2.1 if anyone needs them:
https://huggingface.co/hrishioa/wasm-OpenHermes-2.5-Mistral-7B-q4f32_1
https://huggingface.co/hrishioa/mlc-chat-dolphin-2.2.1-mistral-7b-q4f32_1

https://github.com/mlc-ai/web-llm/assets/973967/2ff46f5d-a916-44bf-b066-6fdfee3fb77c


Runs pretty well at q4f32

**Comment by CharlieFRuan** [comment]
Thanks for contributing and sharing the results! Currently working on incorporating Mistral into web-llm; will support `sliding_window` and `sliding_window_chunk_size`!

**Comment by CharlieFRuan** [comment]
The new [0.2.9 npm](https://www.npmjs.com/package/@mlc-ai/web-llm) now supports Mistral with [sliding window attention](https://arxiv.org/pdf/2310.06825.pdf), supporting a 4096 window size, removing the notion of max context length! 

This is reflected in the demo:
![image](https://github.com/mlc-ai/web-llm/assets/53290280/133dbc14-47eb-4512-ba04-f42fe805e9bf)

**Comment by bokuweb** [comment]
@CharlieFRuan Thanks. I used following model. it works 🎉 

https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Llama-2-7b-chat-hf-q4f32_1-webgpu.wasm

**Comment by jparismorgan** [comment]
Hi there, I am trying to use https://huggingface.co/spaces/Felladrin/Web-LLM-Mistral-7B-OpenOrca with `"@mlc-ai/web-llm": "0.2.14",` but I'm getting:
```
app-index.js:31 [llm@initChat] Error: Cannot find global function vm.builtin.param_module_from_cache_by_name
    at Instance.getGlobalFuncInternal (webpack-internal:///(:3001/app-pages-browser)/../../node_modules/.pnpm/@mlc-ai+web-llm@0.2.14/node_modules/@mlc-ai/web-llm/lib/index.js:2350:23)
    at eval (webpack-internal:///(:3001/app-pages-browser)/../../node_modules/.pnpm/@mlc-ai+web-llm@0.2.14/node_modules/@mlc-ai/web-llm/lib/index.js:2164:29)
    at new RuntimeContext (webpack-internal:///(:3001/app-pages-browser)/../../node_modules/.pnpm/@mlc-ai+web-llm@0.2.14/node_modules/@mlc-ai/web-llm/lib/index.js:1464:47)
    at new Instance (webpack-internal:///(:3001/app-pages-browser)/../../node_modules/.pnpm/@mlc-ai+web-llm@0.2.14/node_modules/@mlc-ai/web-llm/lib/index.js:2161:24)
    at eval (webpack-internal:///(:3001/app-pages-browser)/../../node_modules/.pnpm/@mlc-ai+web-llm@0.2.14/node_modules/@mlc-ai/web-llm/lib/index.js:3224:20)
```
Is this a known issue? If not, is this something we could take a look at fixing? Thank you!

**Comment by CharlieFRuan** [comment]
I am not too sure what model library this is using: https://huggingface.co/spaces/Felladrin/Web-LLM-Mistral-7B-OpenOrca

However, there has been multiple rounds of updates to webllm recently and I have seen this error before. I am guessing that the link uses [our old Mistral model library](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.1-q4f16_1-sw4096_cs1024-webgpu.wasm).

There are two options:
- Change the model library to this backward-compatible (non-SLM) model but recompiled: https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.1-q4f16_1-sw4k_cs1k-webgpu.wasm
- Use the [SLM model library](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/Mistral-7B-Instruct-v0.2-q4f16_1-sw4k_cs1k-MLC-webgpu.wasm), and recompile the OpenOrca weights following https://llm.mlc.ai/docs/deploy/javascript.html#bring-your-own-model-variant.

cc @felladrin
