### ISSUE TITLE
Use modern javascript API

### ISSUE THREAD

**Issue by louis030195** [mlc-ai/web-llm#203]
Callback is a very outdated API, would it be possible to use modern javascript?

```ts
import * as webllm from "@mlc-ai/web-llm";

for await (const response of webllm.chat.completions.create({
    model: 'mistral-7b-chat-hf-q4f32_1',
    stream: true,
    messages,
})) {
  console.log(res)
  // You, can, use, ...
}

```

ideally it would be similar UX that the client side of

https://github.com/vercel/ai

but i guess not everyone use react

**Comment by tqchen** [comment]
This is supported
