### ISSUE TITLE
The download is too slow. Is there any way to improve the download speed

### ISSUE THREAD

**Issue by LoveSlience** [mlc-ai/web-llm#204]
I spent several hours downloading model， Is there any way to improve the download speed， or download it locally and then load it

**Comment by felladrin** [comment]
Yes, you can. You can clone any [mlc-chat repository from HuggingFace](https://huggingface.co/models?search=mlc-chat-) (that has been built for WebGPU) and load them from localhost using a config like this:
```typescript
import * as webLLM from "@mlc-ai/web-llm";

const modelId = "Some-Model-Name-q4f32_1";

const appConfig = {
  model_list: [
    {
      model_url:
        "https://localhost:8080/params/",
      local_id: modelId,
    },
  ],
  model_lib_map: {
    [modelId]:
      "https://localhost:8080/Some-Model-Name-q4f32_1-webgpu.wasm",
  },
};

const chatConfig = {
  temperature: 0,
  repetition_penalty: 1.2,
  top_p: 1
};

const chat = new webLLM.ChatModule();

await chat.reload(modelId, chatConfig, appConfig);
```

**Comment by LoveSlience** [comment]
It works, thanks. I download this modal  [mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0](https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0)。but  I can't find the wasm file,  i have to use an online address
 ` const modelId = "vicuna-v1-7b-q4f32_0";

  const appConfig = {
    model_list: [
      {
        model_url:
          "http://localhost:3000",
        local_id: modelId,
      },
    ],
    model_lib_map: {
      [modelId]:
        "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/vicuna-v1-7b-q4f32_0-webgpu-v1.wasm",
    },
  };

  const chatConfig = {
    temperature: 0.7,
    repetition_penalty: 1.2
  };`

**Comment by LoveSlience** [comment]
It works, thanks. I download this modal [mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0](https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0)。but I can't find the wasm file, i have to use an online address。`const modelId = "vicuna-v1-7b-q4f32_0";

const appConfig = {
model_list: [
{
model_url:
"http://localhost:3000",
local_id: modelId,
},
],
model_lib_map: {
[modelId]:
"https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/vicuna-v1-7b-q4f32_0-webgpu-v1.wasm",
},
};

const chatConfig = {
temperature: 0.7,
repetition_penalty: 1.2
};`

**Comment by LoveSlience** [comment]
Thank you very much, I download this modal [mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0](https://huggingface.co/mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0) but I can't find the wasm file. I can only use an online address or download it locally separately. Can you add wasm files to the warehouse 
```
const modelId = "vicuna-v1-7b-q4f32_0";

const appConfig = {
    model_list: [
      {
        model_url:
          "http://localhost:3000",
        local_id: modelId,
      },
    ],
    model_lib_map: {
      [modelId]:
        "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/vicuna-v1-7b-q4f32_0-webgpu-v1.wasm",
    },
  };

const chatConfig = {
    temperature: 0.7,
    repetition_penalty: 1.2
  };
```

**Comment by felladrin** [comment]
Great to see you got it working, @LoveSlience!
That's good that you pointed that out. I've updated my comment above to clarify that for future readers.

About `mlc-ai/mlc-chat-vicuna-v1-7b-q4f32_0`, unfortunately, I can't change that repo, as I'm not part of the mlc-ai team. But you can still download [that .wasm](https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/vicuna-v1-7b-q4f32_0-webgpu-v1.wasm) and put in the same folder that you're serving the params (http://localhost:3000), so you could load it as 
```
    model_lib_map: {
      [modelId]:
        "http://localhost:3000/vicuna-v1-7b-q4f32_0-webgpu-v1.wasm",
    },
```
