### ISSUE TITLE
Chat demo does not work on Android because of maxStorageBufferBindingSize 

### ISSUE THREAD

**Issue by beaufortfrancois** [mlc-ai/web-llm#209]
On my Pixel 7 Android device, the [maxStorageBufferBindingSize](https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxstoragebufferbindingsize) limit is only 128. Sadly https://webllm.mlc.ai/#chat-demo requires 1024 for the `Llama-2-7b-chat-hf-q4f16_1` model as seen below when run on Chrome for Android. 

As it is possible with an Android app (https://llm.mlc.ai/#android), would it be possible to lower this limit so that more Android devices can access and play with https://webllm.mlc.ai/#chat-demo? Note that WebGPU support is coming to Android soon. See https://groups.google.com/a/chromium.org/g/blink-dev/c/YFWuDlCKTP4/m/97C4LCBUBgAJ

![image](https://github.com/mlc-ai/web-llm/assets/634478/5c6e6e9c-c33b-46b4-8682-a29383b6b88b)

**Comment by beaufortfrancois** [comment]
It seems related to https://github.com/apache/tvm/pull/14640

**Comment by beaufortfrancois** [comment]
How can the Chrome team assist you in addressing this limitation? The `maxStorageBufferBindingSize` WebGPU limit is actually derived from Vulkan's [`maxStorageBufferRange`](https://vulkan.gpuinfo.org/displayreport.php?id=23691#properties:~:text=maxStorageBufferRange) limit.

**Comment by tqchen** [comment]
Get it, let us look a bit into it and see if it is possible to get a variant of small model that fit into this limit. In the meantime, I feel that the vulkan driver should be able to lift some of the limit, but of course that would require changes to the vulkan driver end

**Comment by CharlieFRuan** [comment]
Hi @beaufortfrancois, the demo now has three models (ones with `-1k` suffix) that should be able to run with 128MB: https://webllm.mlc.ai/

**Comment by beaufortfrancois** [comment]
First of all, thanks for providing those models! 

I've just tried the `Llama-2-7b-chat-hf-q4f16_1-1k` model in Chrome Canary for Android where WebGPU is enabled by default and as you can see below, the never-ending answer seems wrong when asking "Which color is the dress?". Is this an issue in the model or in the implementation?

Note that it works great on "Apple M1 Pro" device.

https://github.com/mlc-ai/web-llm/assets/634478/177d4dcb-8889-4938-b4f5-c80255f6a68c

**Comment by beaufortfrancois** [comment]
> that model depends on shader-f16 feature, which only existed in chrom canary (and not chrome stable AFAIK), so not sure if it works on android. If it is possible to get the console output, it will also help us see what is going on

`shader-f16` is shipping in Chrome 120. See https://groups.google.com/a/chromium.org/g/blink-dev/c/AsKn-UwMYAE/m/4FKB-x_QAQAJ

I'm unable to get logs as Chrome is now crashing with this model. Sorry ;( I've tried several times.

> Do you mind trying out RedPajama-INCITE-Chat-3B-v1-q32-1k?

It works great with `RedPajama-INCITE-Chat-3B-v1-q4f32_1-1k`.


<img width="1376" alt="Screenshot 2023-11-13 at 15 06 22" src="https://github.com/mlc-ai/web-llm/assets/634478/92092037-5936-43a6-ac49-c053717da0b3">

**Comment by tqchen** [comment]
It is possible that the model crashes in Llama, we are hitting quite a bit of limit in Llama2 model, and in iOS we had to rely on 3bit quantization. So likely 3B model would be preferred choice.

Glad that RedPajama-INCITE-Chat-3B-v1-q4f32_1-1k works, perhaps you can also try RedPajama-INCITE-Chat-3B-v1-q4f16_1-1k to test f16 support

**Comment by tqchen** [comment]
Glad that 3B model works, this is the first running example webgpu native LLM on mobiles AFAIK, thank you @beaufortfrancois  for pushing this

**Comment by beaufortfrancois** [comment]
> It is possible that the model crashes in Llama, we can hit VRAM limit in Llama2 models(that goes beyond 4GB) when using 4 bit quantization, and in iOS we had to rely on 3bit quantization to stay in memory budget. On android we can sometimes get Llama2 4bit model working but that also requires to go beyond 4GB VRAM limit and the depending on the system limit and phone's capability it can crash.

🥳  I was finally able to get logs! 

```
[FATAL] /ssd1/cfruan/packages/tvm-unity/src/runtime/memory/memory_manager.cc:108: InternalError: Check failed: (offset + needed_size <= this->buffer.size) is false: storage allocation failure, attempted to allocate 8396800 at offset 0 in region that is 8388608bytes
put_char @ worker.360c8a9c.js:669

Uncaught (in promise) DOMException: Failed to execute 'mapAsync' on 'GPUBuffer': Device is lost
```

<img width="1840" alt="Screenshot 2023-11-13 at 15 42 56" src="https://github.com/mlc-ai/web-llm/assets/634478/912e8c40-c29e-4301-9e22-b1ca50b88cb0">

Hopefully this will help.

> So likely 3B models are good choice to demo LLM on android/webgpu, or if later we have 2bit model variants. Glad that RedPajama-INCITE-Chat-3B-v1-q4f32_1-1k works, perhaps you can also try RedPajama-INCITE-Chat-3B-v1-q4f16_1-1k to test f16 support

<img width="1376" alt="Screenshot 2023-11-13 at 15 36 48" src="https://github.com/mlc-ai/web-llm/assets/634478/0023fd64-0939-4927-84cf-3f611a106bc2">

> Glad that 3B model works, this is the first running example of webgpu native LLM on mobile phone AFAIK, thank you @beaufortfrancois for pushing this. Love to share this with broader community and let us know how we can help

I'm also really happy 😄  to see WebLLM running on Android without any flag ;)

**Comment by tqchen** [comment]
The error log indeed indicate possible OOM ("gpu get lost") because the model is too VRAM demanding

**Comment by beaufortfrancois** [comment]
> The error log indeed indicate possible OOM ("gpu get lost") because the model is too VRAM demanding

Is there a way at the runtime to know this device won't work properly? Is there a GPU adapter limit ( https://gpuweb.github.io/gpuweb/#gpusupportedlimits) you could tie this to? The two other ones work great.

**Comment by tqchen** [comment]
We need to know the total amount of VRAM that can be allocated. In Vulkan I think should corresponds to `PhysicalDeviceMemoryProperties ` and memory heap size.  

Note that there is also a system cap, since we are using unified memory in ARM chips, the SoC can have 8G but may limit the gpu to only use 4G.

I am not sure if there is an exact correspondence in the spec. `maxBufferSize` limits the size of buffer we can allocate per alloca, but we need total allocable memory size .

**Comment by beaufortfrancois** [comment]
In the meantime, it is possible to react to "out-of-memory" GPU errors. See https://gpuweb.github.io/gpuweb/#error-scopes
```js
device.pushErrorScope('out-of-memory');
// ...
device.popErrorScope().then((error) => {
  console.error(error.message);
});
```

**Comment by beaufortfrancois** [comment]
> We need to know the total amount of VRAM that can be allocated. In Vulkan I think may corresponds to `PhysicalDeviceMemoryProperties ` and memory heap size. Note that there can also be a system cap, since we are using unified memory in ARM chips, the SoC can have 8G but may limit the gpu to only use 4G.

From what I understand, exposing this raw value won't be possible in WebGPU due to obvious privacy concerns.

**Comment by beaufortfrancois** [comment]
It's not clear to me if reacting to "out-of-memory" GPU errors should happen in WebLLM or in Apache TVM?

**Comment by CharlieFRuan** [comment]
Will take a look later this week!

**Comment by beaufortfrancois** [comment]
@CharlieFRuan Did you have a chance to look at it?

**Comment by CharlieFRuan** [comment]
@beaufortfrancois I looked into it but had trouble replicating the OOM  webGPU error on my device (a Macbook)...

Could you help me triage a bit? Specifically, do you see this piece of log every time the issue happen?
```
[FATAL] /ssd1/cfruan/packages/tvm-unity/src/runtime/memory/memory_manager.cc:108:
InternalError: Check failed: (offset + needed_size <= this->buffer.size) is false: 
storage allocation failure, attempted to allocate 8396800 at offset 0 in region that is 8388608bytes
@ worker.360c8a9c.js:669
```

From my understanding, whenever you see this log, it means that we have caught the error, and the UI would tell the user about `Generate error` (like the screenshot below):
<img width="1136" alt="Screen Shot 2023-11-20 at 11 25 13 AM" src="https://github.com/mlc-ai/web-llm/assets/53290280/fe16fccb-967f-4849-993b-91d588588eee">

Therefore, under what circumstance do you encounter the demo just output gibberish without raising an error like your earlier comment?

> I've just tried the `Llama-2-7b-chat-hf-q4f16_1-1k` model in Chrome Canary for Android where WebGPU is enabled by default and as you can see below, the never-ending answer seems wrong when asking "Which color is the dress?". Is this an issue in the model or in the implementation?
> 
> Note that it works great on "Apple M1 Pro" device.
> 
>  screen-20231113-091318.mp4

Thank you! Let me know if I misunderstood something.

**Comment by CharlieFRuan** [comment]
Hi @beaufortfrancois, thanks for the confirmation; I just got my hands on a Samsung Galaxy S23 to try to reproduce and hopefully catch the OOM error (after concluding that non-mobile devices perhaps cannot reproduce the OOM error).

However, when I go to webgpureport.org, `requestAdapter` says `failed` (leading to failure of web-llm), and logs above say:
```
webgpu request with adapterOptions: {"powerPreference": "high-performance"} failed: Cannot read properties of null (reading 'isFallbackAdapter')
webgpu request with adapterOptions: {"powerPreference": "low-power"} failed: Cannot read properties of null (reading 'isFallbackAdapter')
webgpu request with adapterOptions: {compatibilityMode: true} failed: Cannot read properties of null (reading 'isFallbackAdapter')

webgpu appears to not be supported
```

I set webgpu to enabled in `chrome://flags`, using the latest chrome version 119.0.6045.163. I wonder if you happen to know about the error above and whether Galaxy S23 supports webgpu at all... Otherwise, I might have to guesstimate the implementation and hope that it catches the error.

Thanks in advance! Besides, I might have limited availability until next week because of Thanksgiving.

**Comment by beaufortfrancois** [comment]
WebGPU is available without a flag in [Chrome Canary for Android](https://play.google.com/store/apps/details?id=com.chrome.canary).

> Thanks in advance! Besides, I might have limited availability until next week because of Thanksgiving.

Enjoy 🦃

**Comment by beaufortfrancois** [comment]
@CharlieFRuan Did you have a chance to look at this issue?

**Comment by CharlieFRuan** [comment]
@beaufortfrancois Unfortunately not yet... Sorry for the delay, have been caught up with various other things. But this is still something in my mind and I'll see if I can do it this weekend/early next week.

**Comment by CharlieFRuan** [comment]
@beaufortfrancois Got Android development workflow going; and was able to crash. Tried the `device.pushErrorScope()` and it's not able to catch the error for me before it crashes; at least on the web-llm side. Though the error should be inside `reload()`, around the `fetchNDArrayCache()`. Did you have to do anything to get the log "mapAsync on GPUBuffer device is lost"? Or you were just running the demo, and it is based on luck whether it throws the error? I might need to look into TVM to catch the error.
<img width="636" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/16fac7a8-5793-4d2f-b573-c88a663a37b2">
<img width="1062" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/b2f39e9f-ab9c-4c63-a1a1-067748cccef7">

**Comment by beaufortfrancois** [comment]
> Or you were just running the demo, and it is based on luck whether it throws the error?

Exactly. I was "just" running the demo.

**Comment by beaufortfrancois** [comment]
WebGPU will ship in Chrome 121 on Android in 2 weeks and it'd be nice if WebLLM demo does not crash, or at least, can handle it. Let me know how I can help further @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Thanks for the timeline! Will keep you updated.

**Comment by patnorris** [comment]
Those are exciting news, thank you for sharing them @beaufortfrancois !
I got the 3B param model running on Android via the app I've been developing and would be interested to get the 7B Llama2 model working as well :) If I can help you with debugging or otherwise, please let me know @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Hey @patnorris, thanks for your interest and for offering help! However, as of now, it does not seem to be possible to run Llama 2 7B (even the 1k context length) on Android via Chrome. Perhaps you could check out https://llm.mlc.ai/docs/deploy/android.html.

@beaufortfrancois  https://github.com/mlc-ai/web-llm/pull/256 is my attempt to address this issue. We tried various ways of catching the crash, including [propagating error from tvm](https://github.com/apache/tvm/pull/16330) and using [device.lost.then](https://github.com/gpuweb/gpuweb/blob/main/design/ErrorHandling.md#fatal-errors-requestadapter-requestdevice-and-devicelost). However, they don't seem to be reliable and Chrome would keep asking for memory until it crashes (with the "Aw Snap" crash page).

As a result, we decided to disable such models altogether on the demo page for Android so that users do not experience crashing. We predict whether the device would crash based on what `maxStorageBufferBindingSize` is used (assuming that if it is `128MB`, then this device cannot run large models).

Currently, only 1k-context-length Redpajamas are selectable for Android. I will add more before Chrome 121 shipping.

Feel free to review and leave comments on that PR.

**Comment by toji** [comment]
I just tried https://webgpureport.org/ on a Pixel 7 with Chrome Canary 122.0.6233.0, which worked as expected. Then I updated to 122.0.6237.0, which also worked as expected. It's possible that an intermediate Canary build broke WebGPU but if so it appears to be resolved now. Thus is the nature of nightly builds. :shrug:

I'll take a look on my end and see if there's some way for us to reliably catch this crash and surface it as a device loss. If it's being communicated through Vulkan according to spec then I think it really should already be firing. It's possible that it's provoking some deeper, system-level crash, though, and if that's the case I don't know how much we can do about it.

**Comment by CharlieFRuan** [comment]
@toji Thanks for chiming in! Canary is working on my Android again!

Regarding the crash, please let me know if you need any information from me.

**Comment by beaufortfrancois** [comment]
For info, here's the final output of `adb logcat` when Android kills Chrome Canary when I can't interact with it anymore:

```
lmkd  Kill 'com.chrome.canary:privileged_process0' (7798), uid 10386, oom_score_adj 0 to free 5161192kB rss, 183376kB swap; reason: device is low on swap (377032kB < 3145724kB) and thrashing (412%)
lmkd  Kill 'com.chrome.canary' (7685), uid 10386, oom_score_adj 0 to free 61488kB rss, 97804kB swap; reason: device is low on swap (613764kB < 3145724kB) and thrashing (477%)
lmkd  Kill 'com.chrome.canary:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0' (7766), uid 90000, oom_score_adj 0 to free 49872kB rss, 429792kB swap; reason: device is low on swap (598584kB < 3145724kB) and thrashing (316%)
system_server  WIN DEATH: Window{2440115 u0 com.chrome.canary/com.google.android.apps.chrome.Main}
```

**Comment by tqchen** [comment]
@beaufortfrancois let us know if there is anything you need from our end. Seems was due to android chrome taking too much memory. I wonder if limiting the models to 3b models help

**Comment by beaufortfrancois** [comment]
@toji may have insights. From what I understand there's not much you can do from the web app side.

**Comment by tqchen** [comment]
get it, maybe @CharlieFRuan can also confirm once we redeploy the latest that filters out the models, so we only run small models on android

**Comment by CharlieFRuan** [comment]
@tqchen Yep, redeployed already:
<img width="983" alt="Screenshot 2024-01-17 at 11 09 36 AM" src="https://github.com/mlc-ai/web-llm/assets/53290280/38dec91d-89c0-4590-854d-ebbaaaf98f83">

**Comment by tqchen** [comment]
great, @beaufortfrancois feel free to let us know if the latest version works for you and if you need anything from us

**Comment by beaufortfrancois** [comment]
I still see all the models when going to https://webllm.mlc.ai/ in Chrome Canary for Android. Is that expected?
![image](https://github.com/mlc-ai/web-llm/assets/634478/82f3e01e-0d17-410c-b9cf-1440317909bd)

**Comment by CharlieFRuan** [comment]
Hmm this is not expected... Could you share the log? or try clearing cache (not sure it'd help)

**Comment by CharlieFRuan** [comment]
The limit of model is determined by max storage buffer binding size; if it is <= 128MB, then we limit the model. I'd expect your Android has 128MB; would be nice to confirm this from the log.

**Comment by tqchen** [comment]
maybe related to browser cache

**Comment by beaufortfrancois** [comment]
Looking at `about:gpu`, I can see `maxStorageBufferRange` is 2147483648 (2GB), and https://webgpureport.org now says the `maxStorageBufferBindingSize` WebGPU limit on my Pixel 7 device is 2147483644 (almost 2GB) with Chrome Canary (122.0.6250.0).

Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/Limits.cpp;l=58;drc=8e8525164710883e3af381a5c6fea4c8847a90c0

**Comment by CharlieFRuan** [comment]
Hmm that is interesting... My Galaxy S23 is still 128MB with the same Chrome Canary version. 

Good news is that I am guessing your Pixel 7 can run the regular Redpajama (not 1k version). On the other hand we might need to rely on some other approximation for the available vRAM.

**Comment by beaufortfrancois** [comment]
I confirm `RedPajama-INCITE-Chat-3B-v1-q4f16_1` works: prefill: 1.2083 tokens/sec, decoding: 4.3987 tokens/sec

**Comment by CharlieFRuan** [comment]
Thanks for the confirmation; we'll try to come up with another solution for limiting model selection on Android phones with 2GB `maxStorageBufferBindingSize`

**Comment by beaufortfrancois** [comment]
> Hmm that is interesting... My Galaxy S23 is still 128MB with the same Chrome Canary version.

Out of curiosity, what is the `maxStorageBufferRange ` Vulkan limit value in `about:gpu` for your Galaxy S23 device?

**Comment by tqchen** [comment]
wonder if we can rely on adapter info, at least for example in mac it will show up as gpu apple. maybe for android we have a special gpu vendor type?

**Comment by beaufortfrancois** [comment]
Here's the GPU adapter info from https://webgpureport.org on my Pixel 7 device:

![image](https://github.com/mlc-ai/web-llm/assets/634478/0237e5b5-0c17-4a07-9bf4-cd6b6bca8d87)

**Comment by CharlieFRuan** [comment]
Here is our Galaxy S23's:
![Screenshot_20240118_033134_Chrome Canary](https://github.com/mlc-ai/web-llm/assets/53290280/ce0a070a-fc36-4fba-8624-e9dcbb456f25)

**Comment by CharlieFRuan** [comment]
> Out of curiosity, what is the maxStorageBufferRange  Vulkan limit value in about:gpu for your Galaxy S23 device?

134217728, so 128MB as well

**Comment by tqchen** [comment]
I think we should be able to tell mobile gpus by looking at the vendor field and architecture field :)

**Comment by beaufortfrancois** [comment]
FYI https://twitter.com/quicksave2k/status/1747884713757282450

**Comment by CharlieFRuan** [comment]
OOM errors in `createBuffer()` are now able to be caught in webllm npm 0.2.36 via https://github.com/mlc-ai/web-llm/pull/402. If `createBuffer()` does not suffice, will follow up with more error catching in tvmjs. Thanks!

Redeployed https://webllm.mlc.ai/ as well.
