### ISSUE TITLE
[ENH] Add suggestion message when the webgpu is unsupported

### ISSUE THREAD

**Issue by 0dminnimda** [mlc-ai/web-llm#21]
While trying the demo I run into this problem:
```
Find an error initializing the WebGPU device OperationError: Required limit (1073741824) is greater than the supported limit (268435456). - While validating maxBufferSize - While validating required limits
Init error, Error: Find an error initializing WebGPU: OperationError: Required limit (1073741824) is greater than the supported limit (268435456). - While validating maxBufferSize - While validating required limits
```

The rason for this is not using the latest chrome, it is pretty clearly stated in the instructions section, but the error could at least suggest this, because I imaging a lot of people like me to just rush to try the demo without much reading. This can cause a lot of pointless error repots.

**Comment by jinhongyii** [comment]
just pushed a commit to add this message on the website

**Comment by 0dminnimda** [comment]
@jinhongyii [I don't think it'll cut it](https://github.com/mlc-ai/web-llm/issues/22#issuecomment-1510456349)
I envisioned something like a popup in the "chat" so users will definitely notice it

My point is that most don't read those instructions and jump straight to usign the demo

**Comment by 0dminnimda** [comment]
Or at least move the message closer to the chat and make it stand out

**Comment by tqchen** [comment]
Thank you for your suggestion, we have made an update to the API so the error is more clear https://github.com/apache/tvm/pull/14640
