### ISSUE TITLE
Error : Generate error, Error: Chat module not yet initialized, did you call chat.reload?

### ISSUE THREAD

**Issue by iamshreeram** [mlc-ai/web-llm#212]
Hi, Seeing below error while trying it from [web llm chat demo](https://webllm.mlc.ai/#chat-demo)

```
Generate error, Error: Chat module not yet initialized, did you call chat.reload?
```

<img width="1687" alt="image" src="https://github.com/mlc-ai/web-llm/assets/7752805/f2f81c5c-9704-4136-b4e5-fe2a49f39d2c">

**Comment by CharlieFRuan** [comment]
Hi, which browser are you using? We recommend using Chrome Canary specifically, see more at https://webllm.mlc.ai/

**Comment by iamshreeram** [comment]
@CharlieFRuan , thanks for looking into this. Yes, I was using firefox. 
Below is the console log. 

<img width="785" alt="image" src="https://github.com/mlc-ai/web-llm/assets/7752805/aa1ffb42-c96f-40ef-aa44-b900ae661448">




**With chrome, It takes a lot of time to download, but It works fine.**


Is this llama2 a quantized version? Is there anyway to reduce the size of the model or increase the efficiency of model on the fly? i.e., enabling the model to respond with what it knows from the shard it has and expand its knowledge in the background when the download of all the shards are happening?

**Comment by CharlieFRuan** [comment]
Yes, this is a 4bit quantized version. On top of my mind, I don't think there is a way to start generating without downloading all the parameters of the model (if that is what you are asking). But the second time you run the demo, it should be faster as it is cached. Besides, there is also smaller model like RedPajama (3B parameters).

**Comment by tqchen** [comment]
As of now webgpu may not work in firefox as it was not officially shipped. Chrome would be recommended

**Comment by iamshreeram** [comment]
@CharlieFRuan , @tqchen - sure. thanks for the details.
