### ISSUE TITLE
`resetChat()` causing Mistral model to output scrambled responses

### ISSUE THREAD

**Issue by felladrin** [mlc-ai/web-llm#215]
I noticed that after we reset the chat (by calling `chat.resetChat()`) and ask a new question, the answer becomes scrambled.

Here's a comparison of what happens when we call or don't call `resetChat()` _between each question_. Consider that there's a question behind each of those white texts in the following screenshots. Notice how the answers get more and more incoherent when resetting the chat.

| Calling `resetChat()` | Without calling `resetChat()` |
|--------|--------|
| ![image](https://github.com/mlc-ai/web-llm/assets/418083/72567c34-73d4-4e70-b0bc-de645d04684c) | ![image](https://github.com/mlc-ai/web-llm/assets/418083/77c984d3-84b7-4edd-82f8-9f1cc3a4ce05) | 

I'm guessing it's some issue in the `Mistral-7B-Instruct-v0.1-q4f32_1-sw4096_cs1024-webgpu.wasm`, because when I use the [same model](https://huggingface.co/mlc-ai/mlc-chat-Mistral-7B-Instruct-v0.1-q4f32_1) (exactly the same shards) with another `wasm` (compiled with a version of mlc-llm before the introduction of Mistral model), it doesn't suffer from this issue when calling `resetChat()` between each question.

Note: I'm calling `resetChat()` because in my case, each question can be answered independently.

Is anyone else facing this issue?

**Comment by CharlieFRuan** [comment]
Thanks for raising the issue! This is spotted in mlc-llm as well: https://github.com/mlc-ai/mlc-llm/issues/1274.

This will be fixed by https://github.com/apache/tvm/pull/16132, which will be merged in soon!

**Comment by CharlieFRuan** [comment]
Hi @felladrin, the new `wasm` is updated to reflect the fix. Let us know if there are other issues!

**Comment by felladrin** [comment]
Thank you, @CharlieFRuan! I've just tested the new [Mistral-7B-Instruct-v0.1-q4f32_1-sw4096_cs1024-webgpu.wasm](https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/Mistral-7B-Instruct-v0.1-q4f32_1-sw4096_cs1024-webgpu.wasm) and it's working flawlessly when resetting the chat!
