### ISSUE TITLE
Aborted (missing function)

### ISSUE THREAD

**Issue by demattosanthony** [mlc-ai/web-llm#216]
Getting this error after loading the open hermes 2.5 model

Code for loading chat:

```
// create a ChatModule,
const chat = new webllm.ChatModule();
// This callback allows us to report initialization progress
chat.setInitProgressCallback((report: webllm.InitProgressReport) => {
console.log(report.progress);
});
await chat.reload(
"OpenHermes-2.5-Mistral-7B-q4f16_1",
{},
{
model_lib_map: {
  "OpenHermes-2.5-Mistral-7B-q4f16_1":
    "https://raw.githubusercontent.com/Netonomy/netonomy/main/local-llm-binaries/OpenHermes-2.5-Mistral-7B-q4f16_1/OpenHermes-2.5-Mistral-7B-q4f16_1-webgpu.wasm",
},
model_list: [
  {
    model_url:
      "https://huggingface.co/ademattos/open-hermes-2.5-f16/resolve/main/",
    local_id: "OpenHermes-2.5-Mistral-7B-q4f16_1",
    required_features: ["shader-f16"],
  },
],
}
);
```

![Screenshot_2023-11-26_at_11 00 47_PM](https://github.com/mlc-ai/web-llm/assets/70538060/d57d3165-fd81-45db-846e-68e178ee9744)

**Comment by tqchen** [comment]
Cc @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Hi @demattosanthony, thanks for posting the issue. The error demangles to `tvm::runtime::NVTXScopedRange""NVTXSvopedRange(char const*)` and I've run into this issue before as well.

As a temporary workaround, you can comment out this line:
https://github.com/mlc-ai/relax/blob/9a985714f396d40a08458426423872283b886af8/src/runtime/relax_vm/vm.cc#L531

Then you can re-build everything (tvm, web dependencies) and re-compile OpenHermes; afterwards it should work just fine.

I will work on a better fix this week (hopefully tomorrow).

**Comment by CharlieFRuan** [comment]
Hi @demattosanthony, this should be fixed in https://github.com/apache/tvm/pull/16177.

This will probably be picked into https://github.com/mlc-ai/relax soon; in the mean time you could manually make the corresponding changes in the PR and build from source.

**Comment by CharlieFRuan** [comment]
Closing this issue for now; feel free to open another one if there are further questions.
