### ISSUE TITLE
vm.builtin.param_module_from_cache_by_name error

### ISSUE THREAD

**Issue by OvidijusParsiunas** [mlc-ai/web-llm#221]
Hi.
This is a really great repo and I was previously able to build and use it without any problems. Today I have pulled and also tried cloning a fresh new version of the project and upon attempting to run the chat in the [NextJs](https://github.com/mlc-ai/web-llm/tree/main/examples/next-simple-chat) example it gives me the following error:
`Cannot find global function vm.builtin.param_module_from_cache_by_name`

Here are the steps to reproduce the error:

1. Clone the repo (Mac - Apple M1 Pro)

2. Ran the following command in the project source with no errors:
`./scripts/prep_deps.sh`

3. In `tvm_home/web`:
`npm run i`
`npm run build`
`npm run bundle`

4. In source:
`npm i`
`npm build`

5. In `examples/next-simple-chat`:
`npm i`
`npm run dev`

6. And when I click the `Download Model` button this is what I get:
<img width="650" alt="image" src="https://github.com/mlc-ai/web-llm/assets/18709577/1715aaf8-168a-4ec8-817b-7e9790ac7da1">

This exact sequence of instructions used to work fine last week, hence I believe it is one of the recent commits that are causing it.

I have a feeling that the following new line is not being executed for me, do I need to do anything in this project to make it run?
`TVM_REGISTER_GLOBAL("vm.builtin.param_module_from_cache_by_name")
    .set_body_typed(ParamModuleNode::CreateByName);`
[Link](https://github.com/mlc-ai/relax/blob/9e4e17ca888abd6bf20352fa8b75e22c7a20bfbf/src/runtime/relax_vm/ndarray_cache_support.cc#L341C14-L341C14)

**Comment by CharlieFRuan** [comment]
Hi! We recently made a change to relax and you might need to recompile to model with the up-to-date relax. Apologies for the incovenience.

**Comment by CharlieFRuan** [comment]
> build a custom version of the model without any problems
Buy "building a custom version of the model", are you referring to using mlc-llm to compile the wasm?

**Comment by OvidijusParsiunas** [comment]
Sorry, by saying "building a custom version of the model" I meant - I was able to edit the remix and mlc-llm code to extend its functionality. I will rephrase this now to be more correct.
But the core problem is that I now get the error without editing any code and just using the steps above on a fresh new clone.

**Comment by CharlieFRuan** [comment]
I see, so IIUC you are using the prebuilt `Llama-2-7b-chat-hf-q4f32_1` in the original next example. In that case, we updated all wasms (https://github.com/mlc-ai/binary-mlc-llm-libs/pull/49), so you might need to clear the browser's cache to make it download the new wasm again.

I was able to run it with the repo without any changes: 
<img width="534" alt="Screen Shot 2023-12-07 at 11 43 59 AM" src="https://github.com/mlc-ai/web-llm/assets/53290280/b36b479f-d7a9-42eb-918a-f428c0f4e8db">

**Comment by CharlieFRuan** [comment]
I see, glad the issue is solved!

I usually use this in chrome to clear cache (command+shift+delete on mac): 
<img width="522" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/b603ec03-82d8-4b10-a533-2393511107b1">

**Comment by OvidijusParsiunas** [comment]
Thankyou for the tip!
It unfortunately did not do the trick for me and I had to use `await this.cache.delete(request);` to refresh the cache.
Thankyou for all your help @CharlieFRuan!
