### ISSUE TITLE
How to delete the downloaded model file(s)? I don't know where to find the files.

### ISSUE THREAD

**Issue by majisoubhik01** [mlc-ai/web-llm#222]
Hi there, I recently used the WebLLM website for inferencing and now I wanted to delete the model files so that my computer storage doesn't get full as I am done with my work.

Can someone please help me with the same?

Thanks in advance!

**Comment by tqchen** [comment]
you should be aable to do so in the console. `caches.delete("webllm/model")`

**Comment by majisoubhik01** [comment]
Thanks!

**Comment by majisoubhik01** [comment]
Thanks!
