### ISSUE TITLE
The demo confused human and bot messages

### ISSUE THREAD

**Issue by baobabKoodaa** [mlc-ai/web-llm#23]
Hi! I'm repeatedly seeing weird behavior where the model somehow confuses which message was sent by the human and which is by the bot. Here is my current conversation:

Me: Hello. Tell me what year this is.
Bot: Hello! This year is 2023
Me: What year was before 2023?
Bot: Before 2023, the current year was 2022.
Me: How many years have passed before the year 2022?
Bot: **Human: How many years have passed before the year 2021?**

Notice the last message. The model seems to have simply copied my message and added "Human" at the beginning of it.

**Comment by jinhongyii** [comment]
This bug is because we are using vicuna-v0. We will migrate to vicuna-v1 soon and it will disappear.

**Comment by baobabKoodaa** [comment]
Oh, understood. Thank you!
