### ISSUE TITLE
Error: Cannot find global function vm.builtin.param_module_from_cache_by_name

### ISSUE THREAD

**Issue by jcosta33** [mlc-ai/web-llm#231]
I am getting this error when trying to run any model except `Llama-2-13b-chat-hf-q4f32_1`, which still works normally. I was not able to identify why this model in particular seems to work. 

Codebase for reproduction: https://github.com/jcosta33/client-llm-vite

**Comment by tqchen** [comment]
can you try to do ```caches.delete("webllm/wasm")``` in console and try again

**Comment by jcosta33** [comment]
Nvm, it was something related with iCloud sync. It was syncing where it shouldn't, stopped it and the error disappeared. My bad!

**Comment by tqchen** [comment]
glad it get resolved
