### ISSUE TITLE
npm package ver 0.2.13 does not support new SLIM models.

### ISSUE THREAD

**Issue by ClankPan** [mlc-ai/web-llm#234]
New compilation flow have been supported in mlc-llm and it was added by this [commit](https://github.com/mlc-ai/web-llm/commit/2f4c4ecc3ef540b094878303808a6bde3eeb98cc). However the new version of npm package released 6 days ago dose not still support it.

It would be great if you update it. 

Thanks!

**Comment by tqchen** [comment]
cc @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Hi! Could you show us the error you are seeing when trying to run a SLM model on web LLM?

**Comment by ClankPan** [comment]
Sorry! It was because of cache!

**Comment by ClankPan** [comment]
Sorry! It was because of just cache!
