### ISSUE TITLE
simple chat example "npm start"

### ISSUE THREAD

**Issue by zwilch** [mlc-ai/web-llm#236]
### Win10 
Path: examples/simple-chat

can not follow Readme.md instruction
```
\webllm-npm\web-llm\examples\simple-chat>npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

added 216 packages, and audited 217 packages in 44s

98 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

\webllm-npm\web-llm\examples\simple-chat>npm start

> simple-chat@0.1.0 start
> cp src/gh-config.js src/app-config.js && parcel src/llm_chat.html  --port 8888

```

**command cp unknown**

**Comment by tlopex** [comment]
I think you can change 
`scripts": {
"start": "cp src/gh-config.js src/app-config.js && parcel src/llm_chat.html --port 8888",
"mlc-local": "cp src/mlc-local-config.js src/app-config.js && parcel src/llm_chat.html --port 8888",
"build": "cp src/gh-config.js src/app-config.js && parcel build src/llm_chat.html --dist-dir lib --no-content-hash"
}`
to
`
"scripts": {
"start": "node copy-config.js && parcel src/llm_chat.html --port 8888",
"mlc-local": "node copy-config.js && parcel src/llm_chat.html --port 8888",
"build": "node copy-config.js && parcel build src/llm_chat.html --dist-dir lib --no-content-hash"
}
`
in file examples\simple-chat\package.json for windows10

**Comment by tqchen** [comment]
thanks @tlopex do you mind send a PR

**Comment by tlopex** [comment]
@tqchen Okay, I will do it later.

**Comment by zwilch** [comment]
thank you for the greate example, but should it not be fixed in the source?
