### ISSUE TITLE
vicuna-0b and vicuna-v0

### ISSUE THREAD

**Issue by loretoparisi** [mlc-ai/web-llm#24]
Which are the dfiferences among v[icuna-0b](https://huggingface.co/mlc-ai/web-lm/tree/main/vicuna-0b) and [vicuna-v0](https://huggingface.co/mlc-ai/web-lm/tree/main/vicuna-v0)

**Comment by tqchen** [comment]
vicuna-v0 was part of previous experiment and is no longer relevant, both are based on vircuna v0
