### ISSUE TITLE
Would the FP16 models work in Chrome v120 which supports f16 shaders?

### ISSUE THREAD

**Issue by AshD** [mlc-ai/web-llm#241]
Chrome v120 supports the half-precision floating-point type f16 in WebGPU shaders (WGSL)
https://chromestatus.com/feature/5180552617656320

I tried the Web demo out but got this error.
`Init error, Error: This model requires WebGPU extension shader-f16, which is not enabled in this browser. `

Also, this is an awesome project that brings AI platforms to the browser. 

Thanks,
Ash

**Comment by tqchen** [comment]
likely due to your chrome not being upgraded yet, or due to the underlying GPU hardware not supporting the feature, you can check https://webgpureport.org/

**Comment by AshD** [comment]
Thanks @tqchen for the quick reply. 

My Chrome version shows 120 and is running on Windows 11 Pro 23H2
GPU is RTX 4090 with Nvidia driver version 546.29

```
Chrome is up to date
Version 120.0.6099.110 (Official Build) (64-bit)
```

My WebGPU shows these as features
```
features:
---------
bgra8unorm-storage
depth-clip-control
depth32float-stencil8
float32-filterable
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
```

The FP32 models all work great.

Thanks,
Ash

**Comment by tqchen** [comment]
interesting, indeed shader-16 was not there,  not sure about the reason

**Comment by oscarbg** [comment]
same for me on Linux Chrome 122 dev/canary with NV drivers on Ada

**Comment by AshD** [comment]
There was an issue with Chrome 120 and PC with both Nvidia GPU and Intel UHD graphics that seemed to have blocked shader-16. 

Happy to report that Chrome Version **120.0.6099.217** fixes that issue and the FP16 Models are **working**. 

Closing this issue. 

Thanks,
Ash
