### ISSUE TITLE
How to simulate token streaming in a web worker?

### ISSUE THREAD

**Issue by finom** [mlc-ai/web-llm#242]
Sorry, but it's unclear at the documentation how to make it simulate token streaming. Can you please provide an example on how to do that?

**Comment by lawrencecchen** [comment]
```ts
const result = await chat.generate(text, (progress, current) => {
  console.log(progress, current);
});
```

Generate callback has a second parameter

**Comment by tqchen** [comment]
the latest API support token streaming via OAI style API
