### ISSUE TITLE
Version conflicts with local demo app.

### ISSUE THREAD

**Issue by vladobra** [mlc-ai/web-llm#250]
I have node versions 18 and 20 and once I build a demo app and select the model, I receive:

web_worker.ts:281 Uncaught (in promise) TypeError: crypto.randomUUID is not a function
    at AM.constructor.<anonymous> (web_worker.ts:281:20)
    at Generator.next (<anonymous>)
    at tslib.es6.js:121:71
    at new Promise (<anonymous>)
    at AE (tslib.es6.js:117:12)
    at AM.constructor.resetChat (llm_chat.54531fa5.js:48:4498284)

It looks that Crypto.randomUUID is not supported for the Node above version 12.
But if I downgrade the node to sub-12 versions, it doesn't build the demo anymore.

Any suggestions?

**Comment by vladobra** [comment]
not an issue

**Comment by louis030195** [comment]
> not an issue

what was the solution?

**Comment by louis030195** [comment]
how i faced this issue:

1. ran `examples/simple-chat` on an orangepi (like raspberrypi) (through ssh)
2. loaded the orangepi on my mac browser eg. 192.168 ... 8883

solution was to tunnel the port to local

i guess it's something with security

![image](https://github.com/mlc-ai/web-llm/assets/25003283/f6efdb57-53b2-494e-bba8-26fb6e8be786)

**Comment by louis030195** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by louis030195** [comment]
is there a way to disable this thing? i want to be able to use my app without having to do this tunnel like on my phone won't install a ssh client..
