### ISSUE TITLE
Function tvmjs.array.decode_storage error

### ISSUE THREAD

**Issue by OvidijusParsiunas** [mlc-ai/web-llm#251]
I have recently tried to experiment with the latest changes of the project and have been getting the following error when attempting to use the `Download Model` button in the nextjs example:

```
[FATAL] /ssd1/cfruan/packages/tvm-unity/include/tvm/runtime/packed_func.h:1908: Function tvmjs.array.decode_storage(0: runtime.NDArray, 1: basic_string<char>, 2: basic_string<char>, 3: basic_string<char>) -> void expects 4 arguments, but 3 were provided.
```

<img width="1481" alt="image" src="https://github.com/mlc-ai/web-llm/assets/18709577/c6ff93ef-75eb-4f8c-b7b4-2638537af860">

I have tried to clear the browser cache, attempted to use it on a different port to make sure its not the cache and have cloned a fresh new copy of the project, but this error is still being thrown.

Any help or advice on this would be very helpful. Thankyou!

**Comment by CharlieFRuan** [comment]
Hi, thanks for reporting the issue! It was due to a recent change in `relax` and should be fixed now: https://github.com/mlc-ai/relax/commit/b1df4b085608158b451d4777743d63f9fab3e0e3. 

Assuming that you are building web-llm from source, rerunning [prep_deps.sh](https://github.com/mlc-ai/web-llm/blob/main/scripts/prep_deps.sh) should suffice (step 2 of [build-from-source](https://github.com/mlc-ai/web-llm?tab=readme-ov-file#build-webllm-package-from-source)). If you are setting your own `TVM_HOME` with a local copy of the repo, then pulling the latest change from https://github.com/mlc-ai/relax and then running `prep_deps.sh` afterwards would be enough.

**Comment by patnorris** [comment]
Thank you, upgrading to 0.2.15 fixed the reported issue for me.
Unfortunately, I'm running into another error now: /ssd1/cfruan/packages/tvm-unity/src/runtime/relax_vm/ndarray_cache_support.cc:312: ValueError: Cannot find parameter in cache: model.embed_tokens.q_weight

I'm loading this model:
{
			"model_url": "https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q4f32_1/resolve/main/",
			"local_id": "Llama-2-7b-chat-hf-q4f32_1",
			"model_lib_url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/Llama-2-7b-chat-hf/Llama-2-7b-chat-hf-q4f32_1-ctx4k_cs1k-webgpu.wasm"
		}

and right when it's finished loading, the error occurs.
<img width="936" alt="image" src="https://github.com/mlc-ai/web-llm/assets/23037714/05173128-dfb6-465a-9210-7003dfd92562">

It seems to be coming from getParamsFromCacheByName in relax/web/src/runtime.ts: https://github.com/mlc-ai/relax/blob/b1df4b085608158b451d4777743d63f9fab3e0e3/web/src/runtime.ts#L1408C14-L1408C14

This is the complete error stack:
[FATAL] /ssd1/cfruan/packages/tvm-unity/src/runtime/relax_vm/ndarray_cache_support.cc:312: ValueError: Cannot find parameter in cache: model.embed_tokens.q_weight
put_char @ index-76f430bd.js:3165
write @ index-76f430bd.js:3165
write @ index-76f430bd.js:3165
nQ @ index-76f430bd.js:3165
EQ @ index-76f430bd.js:3165
$func72 @ 00944416:0x21bad
$func81 @ 00944416:0x2230e
$func82 @ 00944416:0x223ba
$func306 @ 00944416:0x2f023
$func180 @ 00944416:0x2bbc4
$func199 @ 00944416:0x2c4fb
$func200 @ 00944416:0x2c54d
$_ZN3tvm7runtime6detail12LogFatalImplERKNSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEiSA_ @ 00944416:0xd6dce
$func1098 @ 00944416:0xb5d05
$func1081 @ 00944416:0xb449a
$func1075 @ 00944416:0xb313a
$func1077 @ 00944416:0xb3694
$TVMFuncCall @ 00944416:0xcc0b2
sA @ index-76f430bd.js:3165
getParamsFromCacheByName @ index-76f430bd.js:3165
LLMChatPipeline @ index-76f430bd.js:3189
(anonymous) @ index-76f430bd.js:3192
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
e @ index-76f430bd.js:3116
Promise.then (async)
n @ index-76f430bd.js:3116
(anonymous) @ index-76f430bd.js:3116
__awaiter$1 @ index-76f430bd.js:3116
reload @ index-76f430bd.js:3189
o @ index-76f430bd.js:18656
(anonymous) @ index-76f430bd.js:4
bubble @ index-76f430bd.js:4
e @ index-76f430bd.js:860

I'm not familiar with the missing param model.embed_tokens.q_weight, do you have an idea how this could be fixed? Please let me know if I can provide any additional info.

**Comment by CharlieFRuan** [comment]
Ahh, you should use https://huggingface.co/mlc-ai/Llama-2-7b-chat-hf-q4f32_1-MLC instead; the HF link you are using is from the old workflow.

For context, we have been going through a revamp on the model compilation workflow and have not fully deprecated the old workflow, hence some lingering prebuilt weights on HF and github binary repo.

HF weights ending in `-MLC` are from the new workflow. `wasm`s inside folders (e.g. the one you are using) are from the new workflow. All others are from the old workflow. `wasm` from old and HF from new are not compatible; vice-versa.

See https://llm.mlc.ai/docs/prebuilt_models.html for all the prebuilt weights and wasms we have compiled by the new workflow (you'll also notice a page comprised of the old ones).

**Comment by OvidijusParsiunas** [comment]
Hi @CharlieFRuan. The update fixed the issue for me!

Thankyou very much!

**Comment by patnorris** [comment]
Awesome, that worked, thanks a lot @CharlieFRuan !
