### ISSUE TITLE
Init error, Error: This model requires WebGPU extension shader-f16

### ISSUE THREAD

**Issue by tujiu2022** [mlc-ai/web-llm#254]
when I run the web llm,the error:
Init error, Error: This model requires WebGPU extension shader-f16, which is not enabled in this browser. You can try to launch Chrome Canary in command line with flag "--enable-dawn-features=allow_unsafe_apis".
then, I downlaod the Chrome Canary and run 【chrome.exe --enable-dawn-features=allow_unsafe_apis】,but it does not work.
so,help!!!

**Comment by tujiu2022** [comment]
Thanks  @CharlieFRuan for the quick reply.
i check my computer: whe chrome version is new（122.0.6228.0 canary ），but it does not support the shader-f16:
![image](https://github.com/mlc-ai/web-llm/assets/103033429/63c0b292-4c2f-473e-8ad8-2dff52d1a6dd)

maybe the hardwae of rtx3060 cause it.

**Comment by CharlieFRuan** [comment]
That might be the case... It seems that non-apple backends need some time to catch up with shader f16. Meanwhile I'll add more f32 variants in `simple_chat` and hence our demo page.

**Comment by CharlieFRuan** [comment]
Closing this issue for now as no further action can be taken from this repo. Most prebuilt models WebLLM provides come with `f32` variants. One possibility is to update the browser version when available.

Feel free to open/reopen issues if there are further questions.

**Comment by runvnc** [comment]
Hello, please consider adding support for Nvidia. I have a 2060.
