### ISSUE TITLE
Feature request: JS CDN file  for web LLM

### ISSUE THREAD

**Issue by AshD** [mlc-ai/web-llm#258]
For projects that don't use NPM, Is it possible to create a Javascript version that is deployed on a CDN?

This will make it easier to integrate with ASP.NET projects that don't use NPM. 

Thanks,
Ash

**Comment by flatsiedatsie** [comment]
You can try this one:

https://esm.sh/@mlc-ai/web-llm@0.2.8?bundle-deps

**Comment by gaiborjosue** [comment]
Check this out @AshD: https://www.jsdelivr.com/package/npm/@mlc-ai/web-llm

**Comment by AwokeKnowing** [comment]
@gaiborjosue can you give the minimal js example using that? not sure what to import or call

**Comment by flatsiedatsie** [comment]
I've ran into the same issue where I found it surprisingly difficult integrate WebLLM in a project. I wrote a [cargo-cult-ish modification of the source code](https://github.com/mlc-ai/web-llm/issues/380) to get around this. You solution would be cleaner.

> add return Date at top of the getPerformance function

I can't find that function in the file? Where should I modify that?

**Comment by gaiborjosue** [comment]
Oh wow, thanks so much @AshD! I was running into the same issue in the morning. Thanks for posting the solution:)

**Comment by gaiborjosue** [comment]
Hi @flatsiedatsie the file @AwokeKnowing is talking about is: https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm@0.2.35/lib/index.js

**Comment by flatsiedatsie** [comment]
I just re-implemented WebLLM in my project for the third time :-) But this time without any hacks, and with an easier upgrade path. Everything works as advertised. Thank you!

**Comment by MohitBurkule** [comment]
> Thanks for all your work and contribution! A similar solution is included in npm 0.2.36, and the following code snippet in https://jsfiddle.net/ should work with no setups:
> 
> // See https://www.npmjs.com/package/@mlc-ai/web-llm documentation.
> import * as webllm from 'https://esm.run/@mlc-ai/web-llm';
> 
> async function main() {
>   const initProgressCallback = (report) => {
>     console.log(report.text);
>   };
>   const selectedModel = "TinyLlama-1.1B-Chat-v0.4-q4f16_1-1k";
>   const engine = await webllm.CreateEngine(
>     selectedModel,
>     {
>       initProgressCallback: initProgressCallback
>     }
>   );
> 
>   const reply0 = await engine.chat.completions.create({
>     messages: [{
>       "role": "user",
>       "content": "Tell me about Pittsburgh."
>     }]
>   });
>   console.log(reply0);
>   console.log(await engine.runtimeStatsText());
> }
> 
> main();
> <img alt="image" width="1206" src="https://private-user-images.githubusercontent.com/53290280/332593576-eed90ffd-805e-46cc-aba9-3b76c6180ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgwMjI5MzAsIm5iZiI6MTczODAyMjYzMCwicGF0aCI6Ii81MzI5MDI4MC8zMzI1OTM1NzYtZWVkOTBmZmQtODA1ZS00NmNjLWFiYTktM2I3NmM2MTgwZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI4VDAwMDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWU4NGQwZjVmM2MyNzU4OWZlNzY0NTAyMmE4ZjcyNDJhZjFmNjY5MjJmMzlhYjJmMjZjMDQwNTc2ZThmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-FsB8OxiBs2mkAJPCBomuxo2rJCh3g6tMTFOQzABrAM">

This no longer works , can somebody help?
