### ISSUE TITLE
tvm/runtime/c_runtime_api.h' file not found

### ISSUE THREAD

**Issue by nico-martin** [mlc-ai/web-llm#263]
Hi there,
I am trying to build web-llm locally on my Windows machine. But it fails to build the dependencies.

```
+ npm --version
9.8.1
+ TVM_HOME_SET=
+ [[ -z '' ]]
+ [[ ! -d 3rdparty/tvm-unity ]]
+ export TVM_HOME=3rdparty/tvm-unity
+ TVM_HOME=3rdparty/tvm-unity
+ cd 3rdparty/tvm-unity/web
+ make
emcc -I/Path/web-llm/3rdparty/tvm-unity -I/Path/web-llm/3rdparty/tvm-unity/include -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -fwasm-exceptions -c -MM -MT dist/wasm/wasm_runtime.bc emcc/wasm_runtime.cc >dist/wasm/wasm_runtime.d
emcc -I/Path/web-llm/3rdparty/tvm-unity -I/Path/web-llm/3rdparty/tvm-unity/include -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/dlpack/include -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/dmlc-core/include -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/compiler-rt -I/Path/web-llm/3rdparty/tvm-unity/3rdparty/picojson -O3 -std=c++17 -Wno-ignored-attributes -fwasm-exceptions -emit-llvm -c -o dist/wasm/wasm_runtime.bc emcc/wasm_runtime.cc
emcc/wasm_runtime.cc:32:10: fatal error: 'tvm/runtime/c_runtime_api.h' file not found
   32 | #include <tvm/runtime/c_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:38: dist/wasm/wasm_runtime.bc] Error 1
```

First, does anyone have an idea how to fix this?

Second, is there a reason that we have to build those dependencies on each machine that wants to build `web-llm`? Wouldn't it be possible to ship the prebuilt `3rdparty` Scripts within the git repo?

**Comment by CharlieFRuan** [comment]
Hi @tlopex, I have the impression that you are on a Windows machine; have you run into this issue before?

**Comment by nico-martin** [comment]
I digged deeper and tried to build 3rdparty/tvm-unity/web manually, which fails:
![image](https://github.com/mlc-ai/web-llm/assets/8424136/685176a5-d79a-4cb7-ab47-26823890507c)
But the IDE can resolve it. So I renamed `tvmjs_runtime_wasi.d.ts` to `tvmjs_runtime_wasi.ts`. Which allowed me to build the lib. But running the `.\scripts\prep_deps.sh` would still produce the same error.

So I published `3rdparty/tvm-unity/web` on npm (https://www.npmjs.com/package/@nico-martin/tvmjs ) to install it the "normal way". This way I was able to install `@nico-martin/tvmjs` and I was finally able to build web-llm.

Wouldn't it make sense to publish `3rdparty/tvm-unity/web` on npm so everyone could use this version instead of building it themselfs?

**Comment by nico-martin** [comment]
@CharlieFRuan is there a reason you did not implemented it in a way like this?
https://github.com/nico-martin/web-llm/tree/build-problem-windows

**Comment by tlopex** [comment]
@CharlieFRuan  Sorry for late reply. I haven't encountered this problem before. 
@nico-martin  Have you tried to rebuild it again? Sometimes installing again can solve the issue.

**Comment by nico-martin** [comment]
Yes, I tried it multiple times, deleted everything, but no luck..

**Comment by CharlieFRuan** [comment]
@tlopex Thanks for sharing!

@nico-martin I guess the main reason `prep_deps.sh` fails is the `make` under `tvm-unity/web` fails, and I am still confused about why that fails on your device; failing `make` is probably why you needed to rename `tvmjs_runtime_wasi.d.ts`.

Glad you figured it out your own. And this is a good idea, we'll make tvmjs an npm package soon. Thanks for the suggestion!
