### ISSUE TITLE
Init error, TypeError: chat.getGPUVendor is not a function

### ISSUE THREAD

**Issue by namtranase** [mlc-ai/web-llm#264]
Thank you for the amazing repo. I had tried the `get-started` example and it worked well. Move to the `simple-chat` example, I got this error:
<img width="876" alt="Screenshot 2024-01-21 at 00 41 45" src="https://github.com/mlc-ai/web-llm/assets/42194884/47ed0232-5dfd-4776-ba34-fa2efea97e7a">

**Comment by CharlieFRuan** [comment]
Try pulling the repo again; this should be fixed now. Apologies for the inconvenience.

**Comment by namtranase** [comment]
Thank you for the quick response, it works now!
