### ISSUE TITLE
Add a way to edit and re-send a message

### ISSUE THREAD

**Issue by hammer-ai** [mlc-ai/web-llm#269]
Hi there, it would be great if there was a way to edit and resend a message, similar to how you can in ChatGPT and other LLM providers. Thank you!

**Comment by CharlieFRuan** [comment]
Now this should be possible in https://chat.webllm.ai/

**Comment by CharlieFRuan** [comment]
Closing this issue as completed. Feel free to reopen/open new ones for further questions.
