### ISSUE TITLE
Error on Android: Cannot find adapter that matches the request

### ISSUE THREAD

**Issue by hmd-ai** [mlc-ai/web-llm#271]
Running `Llama-2-7b-chat-hf-q4f32_1` model on Android throws `Cannot find adapter that matches the request`.

See the demo page: https://webllm.mlc.ai/ on android.

**Comment by CharlieFRuan** [comment]
What device and browser are you using? We'd recommend Chrome Canary; Chrome 121 would work as well after its release.

Could you try if https://webgpureport.org/ works on your Android first?
