### ISSUE TITLE
Ideas for a Refactoring

### ISSUE THREAD

**Issue by nico-martin** [mlc-ai/web-llm#279]
I have recently been working more intensively with WebLLM and have used a fork in my own project to make a few major adjustments. I would like to explain these and stimulate discussion as to whether I should build a PR and how it could look.

https://github.com/nico-martin/tweeter/tree/main/src/webLLM

## Naming
WebLLM depends mainly on two classes: `ChatModule`  and `LLMChatPipeline`. From the name itself it wasn't really clear for me what their main focus is.

Also the naming makes sense for a "Chat Context", but if I use it in an application that runs "Instructions", it could be confusing.

So in my proposel I renamed them like this:
`ChatModule`  ==> `Generator`
`LLMChatPipeline` ==> `Pipeline`

## Models
Right now the ChatModule uses a global "ChatConfig" with all possible LLMs and uses theit `localId` to load one specific LLM.
That I think makes sense for a demo app, where you want to compare different Models. However if I look at it from the perspective of someone who wants to build a product with WebLLM, I will rather focus on one Model and then adjust my prompts or the `Conversation.system` Instructions.

Also I think it would be convenient to have a list of the prebuilt Models in one unified Interface. Therefore I introduces the [`Model` class](https://github.com/nico-martin/tweeter/blob/main/src/webLLM/Model.ts), where [each Model](https://github.com/nico-martin/tweeter/tree/main/src/webLLM/models) would then be an instance of.

The model would then be the parameter you pass to the constructor of the `Generator`.

A possible implementation width both changes would then be the following
```typescript
import Mistral7BInstruct from './models/Mistral7BInstruct';

const generator = new Generator(
  Mistral7BInstruct, // Model
  {
    system:  "[INST] Always assist with care, respect {custom instruction}"
  } //Partial<ConvTemplateConfig>
);
generator.setInitProgressCallback(report => console.log(report));
await generator.load();
const summary = await generator.generate(
  'summarize this Email for me: {...}',
  output => console.log(output ),
);
console.log('Done!', summary);
```

## General Structure

Another improvement I would have in mind would be the following. We could split the library into different modules:

```typescript
// Core
import { Generator } from '@mlc-ai/web-llm';

// Models
import { Mistral7BInstruct, Llama27BChat } from '@mlc-ai/web-llm/models';

// Framework specific implementations
import { useWebLLM } from '@mlc-ai/web-llm/react';
```

The framework-specific implementations in particular, even if they are only relatively simple abstractions, could greatly lower the entry barrier for developers: https://github.com/nico-martin/tweeter/blob/main/src/webLLM/useWebLLM.ts

Let me know what you think. I would love to juggle a few ideas back and forth.

**Comment by CharlieFRuan** [comment]
Hi @nico-martin, really appreciate your thoughts and suggestions, and congrats on the release of your project!

Recently, some of us in the MLC team have also discussed a bit on how we want the WebLLM structure to be like, especially in the near future we want to support things like multimodal models (e.g. chat completion with image input), embedding models, etc (perhaps think the [endpoints in OpenAI APIs](https://platform.openai.com/docs/api-reference/chat)); and low-level APIs, including a logit processor (see https://github.com/mlc-ai/web-llm/pull/277).

The `ChatModule` concept is mainly from our companion project [mlc-llm](https://github.com/mlc-ai/mlc-llm/blob/main/python/mlc_chat/chat_module.py), where there is an almost identical `ChatModule` class for Python runtime as you can see. I resonate with how you mention that the physical semantic of `ChatModule` is unclear -- it is not a model, we need to call `reload()`, etc.

Currently, we are pushing on providing OpenAI-like APIs (see tracker https://github.com/mlc-ai/web-llm/issues/276). Perhaps after that, we'll revisit how to make an extensible code structure, with all the incoming features. I really value your opinions here and will keep you updated!

**Comment by nico-martin** [comment]
Sounds good :). I really like the project and I'm super excited to see how it evolves. So if you need any help, just let me know!

**Comment by CharlieFRuan** [comment]
Thank you!!
