### ISSUE TITLE
Join TMVjs,  mlc-llm and WebLLM 

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/web-llm#281]
I think that there are a lot of issues that comes from TVM and are incorrectly identified here. I.E.

 - #257 
 - #144 
 - #280 

I suggest to do a mono repo with `tvmjs` `web-llm` and `mlc-llm` to be able to cover all the relatedissues

**Comment by DavidGOrtega** [comment]
Indeed the majority of the issues in this repo are related to tvmjs and mlc-llm

**Comment by tqchen** [comment]
there are pros and cons of mono repo, in this case, web-llm focused on a runtime layer of compiled wasm from MLC, so we are ghoing to do separate repos. This being said, we will continuously monitor the requests and update the code, since there are overlaps of developer communities

**Comment by DavidGOrtega** [comment]
Would make sense to transfer issues or at least tag them?

**Comment by tqchen** [comment]
it is ok to keep issues inplace since it would be likely the same group of people handling them, of course we can also cross link

**Comment by DavidGOrtega** [comment]
lets close it for now
