### ISSUE TITLE
Loading models from disk

### ISSUE THREAD

**Issue by bakkot** [mlc-ai/web-llm#282]
I would like more control over where model files live on disk. It would be nice to be able to load files from disk instead of from the web. (I [previously suggested this](https://github.com/mlc-ai/web-stable-diffusion/issues/8) for web-stable-diffusion.)

For implementing this, the drag-and-drop API gives you a [File](https://developer.mozilla.org/en-US/docs/Web/API/File), and those can be used with [createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static) to get a URL, so the only behind-the-scenes change necessary would be for TVM not to [use the cache](https://github.com/apache/tvm/blob/06f7810c4fadd57cc88bd527d1a969941a8bbe28/web/src/runtime.ts#L1545) when reading `blob:` URLs (so as not to double the disk usage). Then you just need a little bit of UI.

**Comment by CharlieFRuan** [comment]
Please checkout the example for uploading model from disk https://github.com/mlc-ai/web-llm/tree/main/examples/simple-chat-upload

**Comment by CharlieFRuan** [comment]
Closing this issue for now, feel free to open new ones
