### ISSUE TITLE
Add Max Token to chat.generate

### ISSUE THREAD

**Issue by emilrowland** [mlc-ai/web-llm#283]
It would be great if there was a max token functionality for the chat.generate method.
Today some models get stuck and output a lot of garbage, if we could limit the model to only output for example 500 tokens then we could return early in these cases.

**Comment by CharlieFRuan** [comment]
Thanks, will add this soon. This should've been included since our `mlc-chat-config.json` has this field.

**Comment by CharlieFRuan** [comment]
Hi @emilrowland! This is supported in npm 0.2.19. For example usage see https://github.com/mlc-ai/web-llm/pull/298
