### ISSUE TITLE
[Technical Debt] getConversation is repeated code

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/web-llm#286]
I do not quite follow the reason of having to define getConversation counterpart of c file. 

I suggest to remove all the code just creating a Conversation with the config file. Is there any time that we are not going to receive one? 

I would probably also keep all the templates in a json file that can be read by c, python or whatever

**Comment by CharlieFRuan** [comment]
A more lightweight way of adding conversation template is indeed something we've been discussing and plan to bring soon https://github.com/mlc-ai/mlc-llm/issues/1485
