### ISSUE TITLE
[Technical debt] Out of memory improvements

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/web-llm#287]
Having tested StableLM1.6 successfully! 🎉 

The model has a 4096 context and its was constantly crashing due to memory errors but I was thinking that I had other problems.
We need a better error handling.

**Comment by CharlieFRuan** [comment]
Thanks for testing, we'll add it to `simple-chat` soon! Would be great if you could share the screenshot or console log.

**Comment by DavidGOrtega** [comment]
Not sure If you needed the screenshot if the error or the model, Im guessing the model so here it is. 
It hallucinates a bit but its pretty interesting. I will tell you how looks my finetune and my continued pretraining
 
<img width="637" alt="image" src="https://github.com/mlc-ai/web-llm/assets/414967/cd08f951-9508-4762-8792-665898e3c402">
