### ISSUE TITLE
[Technical debt] TVMjs dependency 

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/web-llm#290]
Contributing here requires a bit of extra effort. One improvement would be simply publish the TVMjs package and/or the mlc-ai/relax in npm and then change [this line](https://github.com/mlc-ai/web-llm/blob/3319d1c5a93f57425b964c6b3b13e71dcd349d75/package.json#L40)

For seasoned developers of the project that are willing to contribute to TVMjs they have to do it against real TVMjs to then merge to relax, so, they might not dislike the proposed solution that would allow more people to contribute

**Comment by DavidGOrtega** [comment]
One clarification: With this proposal everything falls in the js category, without having to install environments and tvm packages, emscript, etc...

**Comment by nico-martin** [comment]
@DavidGOrtega, I did publish a compiled version of tvmjs on npm: https://www.npmjs.com/package/@nico-martin/tvmjs
Feel free to use this one as long as its not implemented in web-llm.

**Comment by DavidGOrtega** [comment]
@nico-martin thanks!

**Comment by CharlieFRuan** [comment]
This should be resolved by this PR. Now building WebLLM from source only requires `npm install; npm run build`, without needing to run `./scripts/prep_deps.sh`:
- https://github.com/mlc-ai/web-llm/pull/570

Closing this one for now, let us know how we can further improve the experience of contributing to WebLLM!
