### ISSUE TITLE
Support a vision model on webcam live stream

### ISSUE THREAD

**Issue by flatsiedatsie** [mlc-ai/web-llm#291]
It would be very interesting to run a vision model like LLAVA, or the very impressive and tiny new Moondream LLM, in the browser. It would be fantastic if it could analyze images and (live) video.

That would, for example, allow us to create a tool to help blind people to get a sense of the world around them simply by opening a webpage on their phone.

**Comment by CharlieFRuan** [comment]
Yep, multimodal models like LLaVA are on our roadmap as brought up here https://github.com/mlc-ai/web-llm/issues/276
