### ISSUE TITLE
Chat demo appears to be broken

### ISSUE THREAD

**Issue by singerbj** [mlc-ai/web-llm#292]
The chat demo available on https://webllm.mlc.ai/#chat-demo appears to be broken

Would be great to have that up an running :)

![image](https://github.com/mlc-ai/web-llm/assets/3630755/bdc409b8-d6e8-40d0-bba2-ac67a62bd470)

![image](https://github.com/mlc-ai/web-llm/assets/3630755/256bb1f9-8a16-4270-b30c-331ebd68b18a)

**Comment by CharlieFRuan** [comment]
Hi! It seems to be working on my end. Could you check https://webgpureport.org/ to check WebGPU support on your device or browser? We'd recommend using Chrome!

**Comment by singerbj** [comment]
Huh I guess webgpu was disabled on my browser - strange given I'm 99% sure I had the demo working previously on the same machine in the same chrome browser. My browser does say it is "managed by my organization" so maybe that was it. Thanks for the help!
