### ISSUE TITLE
Compatibility with LangChain and Other Ideas

### ISSUE THREAD

**Issue by pcfreak30** [mlc-ai/web-llm#30]
So I have been following the AI boom that's started the past 1-2 months.

I am personally very interested in decentralizing AI models and access. My project (https://lumeweb.com) is in the crypto/web3 space and I am building with https://hypercore-protocol.org. My project is combining a number of Lego blocks as well.

What I am interested in doing, which is something in the distant future ATM based on my current project roadmap, is enabling models to be downloaded from web3 content networks like IPFS, Sia, and Arweave, and then using `HyperDB` that was recently released to read training data.

This data would use hypercores which are basically append-only logs, shared BitTorrent style, aka P2P blockchains.

The result would be the ability to have fully decentralized AI access and distribution over web3. All you would need is the CID of a model and a hash/ID of a stream that would be a vector DB of information.

I am first interested in any thoughts or feedback on this idea, and second, as I can assume LangChain is definitely going to be getting on onboard with vector databases, and how this can integrate with the ecosystem they are building.

Oh and to be clear, my work is purely javascript/typescript so far.

Kudos!

**Comment by tqchen** [comment]
This is a great idea, we have updated the webllm to become a standalone npm package, so it can be composed with other projects
