### ISSUE TITLE
Different instruct based models

### ISSUE THREAD

**Issue by nico-martin** [mlc-ai/web-llm#303]
Hi there,
Did anyone already use other instruction-tuned models than the Mistral 7b?
Maybe like the RedPajama 3b or 7b instruct?
https://huggingface.co/togethercomputer/RedPajama-INCITE-Instruct-3B-v1
https://huggingface.co/togethercomputer/RedPajama-INCITE-7B-Instruct

**Comment by nico-martin** [comment]
I think Gemma 2b and Gemma 7b would be super interresting as well.

**Comment by CharlieFRuan** [comment]
Just added Gemma 2b to https://webllm.mlc.ai/, 7b should be supported soon!

**Comment by CharlieFRuan** [comment]
For anyone wondering, this tutorial may be relevant for adding model variants (i.e. same model library, just different weights): https://llm.mlc.ai/docs/deploy/javascript.html#bring-your-own-model-variant
