### ISSUE TITLE
I get Generate error, Error: WebGPU: cannot factorize big gridDim.x=104197 when I paste text into the box sometimes.

### ISSUE THREAD

**Issue by itissid** [mlc-ai/web-llm#31]
On an M1 Macbook Pro with 16GB running OS 13.1

**Comment by tqchen** [comment]
Thanks for reporting. This was originally due to webGPU's limitation of maxComputeWorkgroupsPerDimension so we spread the launch, we will find ways to fix this as newer version comes with more relaxed limits

**Comment by tqchen** [comment]
should be fixed by https://github.com/apache/tvm/pull/14674, we will update the model after v1 update

**Comment by jinhongyii** [comment]
We have updated to vicuna-v1, and the bug is fixed.
