### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by psmoros** [mlc-ai/web-llm#318]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@0mmadnani) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by tqchen** [comment]
Please send an email to `mlc-llm-private@googlegroups.com`, @CharlieFRuan let us followup and create a SECURITY.md file to point people to reporting email

**Comment by CharlieFRuan** [comment]
Created here: https://github.com/mlc-ai/web-llm/blob/main/SECURITY.md
