### ISSUE TITLE
[TECHNICALDEBT] Put ChatRestModule in shape

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/web-llm#320]
Im not a big fan of `ChatRestModule`, if it disappears I won't miss it at all 😄 . Said that, the code can be improved.
 
 - [ ] parametrize [harcoded endpoint ](https://github.com/mlc-ai/web-llm/blob/63fa2168a6f3f742c9fee36ab46f182d41749e44/src/chat_module.ts#L590)
 - [ ] make it a bit DRYer

**Comment by CharlieFRuan** [comment]
Update: removed it as of now via https://github.com/mlc-ai/web-llm/pull/361

But in the future we still might want to add it back so that webllm can offload to external rest api.
