### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PierrunoYT** [mlc-ai/web-llm#325]
![grafik](https://github.com/mlc-ai/web-llm/assets/95778421/bf276399-786b-4a7d-988d-6a28d28fa6e2)

**Comment by DiegoCao** [comment]
Which Browser did you use for the web-llm?

**Comment by CharlieFRuan** [comment]
Hi! We recommend using the latest version of Chrome. Before trying WebLLM, you can first go to https://webgpureport.org/ to check webgpu availability with your device/browser.
