### ISSUE TITLE
WebCPU?

### ISSUE THREAD

**Issue by fire17** [mlc-ai/web-llm#326]
Hi there! Amazing project!
Was wondering when do you guys think that small models will be able to run on decent smartphones cpus?

For example I'm on 3 year old Samsung Note20
Which is not cutting edge for today but still pretty fast with high performance

![Screenshot_20240306-230743_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/86813ee8-0a5b-41d4-a21a-ca19dc49b651)

It might be slower but I bet this device can squeeze a few tokens per second, if rpis can do it this one definitely can. 
Would love to know if this is on the roadmap and is planned to be supported

Thanks a lot and all the best!

**Comment by fire17** [comment]
Good advice!
Before:
![Screenshot_20240307-070735_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/a8753912-5b2b-4f62-abda-d1aa93961a5d)

After updating chrome:
![Screenshot_20240307-071031_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/7653d8b1-07b5-4998-b037-ba1bb7dbdff2)

I did manage
To squeeze a few tokens per second but
These tiny models are still far from production ready.

![Screenshot_20240307-072421_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/827a46db-c78c-4762-bead-c0090c75cee3)

![Screenshot_20240307-072751_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/726375aa-7f76-4344-95cc-90a547af14d1)

![Screenshot_20240307-072113_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/51b5a593-bbc0-42d1-a829-d068aa4ce9f4)

![Screenshot_20240307-073226_Chrome.jpg](https://github.com/mlc-ai/web-llm/assets/9356048/eed1439d-4ea9-4fa2-b13b-73af872fff49)

Thanks a lot for the advice, wonder if we will see capable 1-bit llms soon, or other tiny but coherent models. 
I'll stay tuned... All the best! 🙏🧘‍♀️

**Comment by tqchen** [comment]
glad it works
