### ISSUE TITLE
Error: Unknown conv template gpt2 when using prebuild gpt2 in examples/get-started

### ISSUE THREAD

**Issue by flores-o** [mlc-ai/web-llm#343]
Hello, I am trying to run examples/get-started with gpt2. See [code changes here ](https://github.com/flores-o/web-llm/commit/3f9ce7890fe641b0430eea161771a1a70c28c83c)

```
  const myAppConfig: webllm.AppConfig = {
    model_list: [
      { 
        "model_url": "https://huggingface.co/mlc-ai/gpt2-q0f16-MLC/resolve/main/",
        "local_id": "gpt2-q0f16",
        "model_lib_url": "https://raw.githubusercontent.com/mlc-ai/binary-mlc-llm-libs/main/gpt2/gpt2-q0f16-ctx1k-webgpu.wasm",
      },
    ]
  }
```

When running the demo, I get this error in the console browser

```
conversation.ts:431 Uncaught (in promise) Error: Unknown conv template gpt2
at getConversation (conversation.ts:431:11)
at new LLMChatPipeline (llm_chat.ts:90:25)
at ChatModule. (chat_module.ts:161:21)
at Generator.next ()
at fulfilled (tslib.es6.js:118:58)
```

When looking into conversation.ts I don't see `conv_template == "gpt2"` even if the docs mention a [gpt2 conversation template ](https://llm.mlc.ai/docs/prebuilt_models.html#gpt2-variant-table)

Any suggestion on how to resolve this? How should the gpt2 conversation template look like cc @CharlieFRuan

**Comment by CharlieFRuan** [comment]
Hi, thanks for raising the issue! This should be solved with the updated conversation template in https://huggingface.co/mlc-ai/gpt2-q0f16-MLC and by updating the web-llm version.

Make sure to clear your cache so that the updated https://huggingface.co/mlc-ai/gpt2-q0f16-MLC can be downloaded.

**Comment by flores-o** [comment]
Thanks @CharlieFRuan. To recap

1. clear the cache 
2. pull latest changes from webllm
3. npm version > 0.2.29
