### ISSUE TITLE
BufferSource argument is empty

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/web-llm#372]
When I try to load the wasm from local using [http-server](https://www.npmjs.com/package/http-server) I have this error no matter if the mime type is `application/wasm` or `application/octet-stream`.

I have used always this server to serve local compiled models without any issue.

```
Uncaught (in promise) CompileError: WebAssembly.instantiate(): BufferSource argument is empty
```

**Comment by CharlieFRuan** [comment]
Thanks for the catch; should be fixed via https://github.com/mlc-ai/web-llm/pull/371/files#diff-28c3e3e43a126ec69590b3e436ce6386f7605089d4964f95146c6bd02a84b01c

**Comment by DiegoCao** [comment]
Thanks, looking into it now
