### ISSUE TITLE
Check failed: (!free_page_ids_.empty()) is false: The KV cache is full. No page can be allocated.

### ISSUE THREAD

**Issue by pilosof** [mlc-ai/web-llm#385]
when prompting to summarize long article or long chat 

* system: macbook pro m1 
* model: llama3

**Comment by CharlieFRuan** [comment]
Thanks for reporting the issue. This error should not be displayed anymore after https://github.com/mlc-ai/web-llm/pull/457, integrated into 0.2.42 and later.

If the request's length exceeds KVCache's context window size, we will throw error. If during decode, the number of generated tokens exceed the context window size, we end the response with finish reason `"length"`.

To fix, try one of the three options:
- Reduce prompt length
- Increase context window size (requires more RAM)
- Use sliding window, set either in `chatOptions` or `overrides`, for more see https://github.com/mlc-ai/web-llm/pull/455
