### ISSUE TITLE
Cache.add() encountered a network error

### ISSUE THREAD

**Issue by thekevinscott** [mlc-ai/web-llm#389]
I'm seeing a `Cache.add()` error when trying to load `Llama-3-8B-Instruct-q4f16_1-MLC`:

```
Error: Cannot fetch https://huggingface.co/mlc-ai/Llama-3-8B-Instruct-q4f16_1-MLC/resolve/main/params_shard_0.bin err= NetworkError: Failed to execute 'add' on 'Cache': Cache.add() encountered a network error
```

<img width="1700" alt="Screenshot 2024-05-06 at 6 03 15 PM" src="https://github.com/mlc-ai/web-llm/assets/151596/f73114a7-e6ea-4cb6-8f4d-9f00ae3268fe">

This is Chrome 124.0.6367.119, running the demo at https://webllm.mlc.ai/

**Comment by thekevinscott** [comment]
Seeing it on a few models, although there doesn't seem to be a rhyme or reason I can see

<img width="714" alt="Screenshot 2024-05-06 at 6 06 25 PM" src="https://github.com/mlc-ai/web-llm/assets/151596/cbe87230-0867-4915-a45c-5376316afac5">

**Comment by thekevinscott** [comment]
I don't _think_ this is related to the typical browser cache, but just for good measure I cleared my cache, but same issue.

**Comment by CharlieFRuan** [comment]
Is this issue encountered for all models? To be honest the `Cache.add()` is a bit vague; I've encountered this when the URL is wrong, but it does not seem to be the case here. 

To triage a bit, could you check, in the console, `application` -> Cache storage, and see if `webllm/config` or `webllm/wasm` are populated? Just wanted to see if this is weight-downloading specific, or also applies to config json file and the wasm.

Besides, is this encountered for all models? Perhaps could you try, say TinyLlama? Wanted to know if it is due to a single weight shard being too large.

**Comment by thekevinscott** [comment]
@CharlieFRuan I've just tried again (same Chrome version) and, lo and behold, it appears to be working. Perhaps there was a new deploy of `webllm` in the meantime?

<img width="304" alt="Screenshot 2024-05-24 at 6 52 08 AM" src="https://github.com/mlc-ai/web-llm/assets/151596/76b3db7e-7866-4d3c-bc91-212fd81ff9d1">

I see entries under Cache storage, but since it now appears to be working, not sure if that's helpful. I wonder if @ucalyptus2 is still seeing the issue.

**Comment by MathisZerbib** [comment]
Hello there i got the same issue here, althought it was mysteriously work on my mobile, maybe I dont have enough space on my pc ? > 5GB

<img width="664" alt="Capture d’écran 2024-09-01 à 22 53 16" src="https://github.com/user-attachments/assets/0962bf17-c119-4193-bffd-149fe538698c">


Here is my cache: 
<img width="947" alt="Capture d’écran 2024-09-01 à 22 54 14" src="https://github.com/user-attachments/assets/65b0679f-ae17-4445-9bfc-a04ea3277f61">


<img width="944" alt="Capture d’écran 2024-09-01 à 22 54 36" src="https://github.com/user-attachments/assets/992930f4-c91b-4cc2-9293-31af72ee3321">

<img width="939" alt="Capture d’écran 2024-09-01 à 22 55 14" src="https://github.com/user-attachments/assets/7c22a5c6-fba2-4b66-aa01-8847d0546cf7">

**Comment by adam91holt** [comment]
I've just been running into this and then I looked at free disk space on my mac and it was 1.8GB! 

I removed about 30GB of files and now everything seems good!
