### ISSUE TITLE
Cannot find WebGPU on Safari (works on Arc)

### ISSUE THREAD

**Issue by louis030195** [mlc-ai/web-llm#392]
nextjs, running in client component

host macos m3

![image](https://github.com/mlc-ai/web-llm/assets/25003283/ab21b546-3e36-4c6c-b632-bb246f0d09fe)

Cannot find WebGPU on Safari (works on Arc, which uses Chromium if I'm not wrong)

Both on MacOS and iPhone

Any idea? How can I provide more info? (not familiar at all with Safari dev, only use it on iPhone usually because Arc does not exist on iPhone)

**Comment by louis030195** [comment]
does not work neither on android (chrome), window (safari)

**Comment by Neet-Nestor** [comment]
WebGPU is not fully supported by all the browsers yet. Please check [WebGPU compatibility table](https://caniuse.com/webgpu) or use https://webgpureport.org/ to check whether the browser you used supports WebGPU.

**Comment by CharlieFRuan** [comment]
Hi @louis030195, Safari should be supported. I tried WebLLM Chat on:
- Macbook: macOS Sonoma 14.5 with Safari Technology Preview
- iPhone: iOS 18.0 Developer Beta with Safari (need WebLLM > 0.2.47: https://github.com/mlc-ai/web-llm/pull/498)

See https://x.com/charlie_ruan/status/1813662385879859472
