### ISSUE TITLE
[feature request] Please allow to upload a model.

### ISSUE THREAD

**Issue by 0wwafa** [mlc-ai/web-llm#421]
In your demo page (which would be nicer as a web app (PWA) you have a list of models.. and that's ok...
But if like in my case, someone has a slow connection and already has some models downloaded in gguf format,
it would be nice to just "upload them" (i.e. load from disk) and try them out.

**Comment by CharlieFRuan** [comment]
For the record, https://github.com/mlc-ai/web-llm/tree/main/examples/simple-chat-upload is an example of supporting local model in the app

**Comment by 0wwafa** [comment]
> For the record, https://github.com/mlc-ai/web-llm/tree/main/examples/simple-chat-upload is an example of supporting local model in the app



> For the record, https://github.com/mlc-ai/web-llm/tree/main/examples/simple-chat-upload is an example of supporting local model in the app

I checked it but I don't get it... sorry

**Comment by Neet-Nestor** [comment]
Thanks @CharlieFRuan for the reference.

@0wwafa Since this is for the webapp instead of the engine, I'll close this issue and create another at https://github.com/mlc-ai/web-llm-chat/issues/23 . Please feel free to follow up there.
