### ISSUE TITLE
Embeddings Example?

### ISSUE THREAD

**Issue by ggaabe** [mlc-ai/web-llm#438]
Hi, I was wondering if there's any chance there could be an embeddings example made with this project?

Someone had asked about it before here:
https://github.com/mlc-ai/web-llm/issues/270

And the example that's linked doesn't seem to actually use this project package at all.

**Comment by CharlieFRuan** [comment]
Thanks for the question! Embedding models were supported in MLC-LLM a month ago (https://github.com/mlc-ai/mlc-llm/pull/2249) and hence there is no technical blocker to support in WebLLM but only a matter of time. Will be a TODO from us, hopefully within weeks

**Comment by ggaabe** [comment]
any chance this might happen soonish?

**Comment by Bert0324** [comment]
any updates

**Comment by CharlieFRuan** [comment]
Hi @ggaabe  @Bert0324, npm 0.2.60 has initial support for embedding and RAG, check out usage here: https://github.com/mlc-ai/web-llm/tree/main/examples/embeddings

Currently only [snowflake-arctic-embedding](https://huggingface.co/Snowflake/snowflake-arctic-embed-m) is supported.

Closing for now, feel free to open new issues.
