### ISSUE TITLE
cleanModelUrl breaks the ability to specify branch names other than 'main'

### ISSUE THREAD

**Issue by bdpoff** [mlc-ai/web-llm#443]
A recent change in #435 streamlined the ModelRecord so that only a partial URL is provided and the full URL is built by the `cleanModelUrl` function. This unfortunately breaks the ability to use model repository branches other than `main`. If that's something you'd like to continue to support, I submitted a small PR (#442) which supports both URL formats. If you're intending to enforce a standardized URL format, I'll close the PR, just thought I'd submit it since it was a small change.

**Comment by CharlieFRuan** [comment]
Thank you! Appreciate the change; left a minor note on the PR

**Comment by bdpoff** [comment]
Fixed in #442
