### ISSUE TITLE
Model request: a dedicated coding model

### ISSUE THREAD

**Issue by flatsiedatsie** [mlc-ai/web-llm#449]
I could have sworn I saw CodeLlama 7B in WebLLM at some point, but it must have been a hallucination.

I was wondering if WebLLM could add support for a dedicated code instruct model. Something around 7B perhaps?

It seems there are discussions on Reddit about which coding model is good about every single week. The latest one being [this one (May 2024)](https://www.reddit.com/r/LocalLLaMA/comments/1crlfu5/best_coding_llm_as_of_may_2024/).

**Comment by CharlieFRuan** [comment]
As you have probably noted, `Qwen2.5-Coder-1.5B` and `Qwen2.5-Coder-7B` are added to the prebuilt list as of `^0.2.63`. Will close this issue for now, feel free to open new ones for other requests!
