### ISSUE TITLE
DOM manipulation (use case: filtering web search results locally)

### ISSUE THREAD

**Issue by eMPee584** [mlc-ai/web-llm#465]
Web search results today have become abhorrently useless, since most search engines have cranked up the fuzzy factor sky high and usually show results matching **_any_** instead of **ALL** provided search terms. A solution could be to show an LLM two items in the results so it can grok the DOM structure and give it keywords to filter in/out items.

I was looking for an extension to do this but couldn't find what i'm looking for, but this seems to provide the infrastructure so I thought why not propose this here ; )

**Comment by eMPee584** [comment]
Uhm, actually found what I was looking for (<https://github.com/proton/better-amazon>) but leaving this open for inspiration, feel free to close at your own discretion.

**Comment by Neet-Nestor** [comment]
I'm glad you found what you need and thanks for your idea! This may be a great potential for feature for our agent browser plugins and we will keep it in our minds. :)
