### ISSUE TITLE
[Tracking] Improve error handling by having customized error types

### ISSUE THREAD

**Issue by Neet-Nestor** [mlc-ai/web-llm#470]
Currently web-llm is throwing `Error` with customized messages. This makes it hard for users to catch a specific kind of error since users must check the message and once the message updates the catch won't work.

We should consider creating different types of Error classes and throw them instead so users can easily catch them and handle accordingly.

**Comment by talperetz** [comment]
+1

**Comment by talperetz** [comment]
Specifically a fix / custom error for `Check failed: (token_id >= 0 && token_id < init_ctx_->vocab_size) is false: Invalid token id 128287 for GrammarStateMatcher` would be great!

It's very common.

**Comment by Neet-Nestor** [comment]
https://github.com/mlc-ai/web-llm/pull/492
