### ISSUE TITLE
Please ensure you have called `MLCEngine.reload(model)` to load the model before initiating chat operations

### ISSUE THREAD

**Issue by radiantone** [mlc-ai/web-llm#477]
Tried the example code from langchain and it throws exception in Google chrome.
web-llm 0.2.46

```
const model = new ChatWebLLM({
  model: 'Phi-3-mini-4k-instruct-q4f16_1-MLC',
  chatOptions: {
    temperature: 0.5,
  },
});
const response = await model.invoke([
  new HumanMessage({ content: "What is 1 + 1?" }),
]);
```

```
Error: Model not loaded before calling chatCompletion(). Please ensure you have called `MLCEngine.reload(model)` to load the model before initiating chat operations, or initialize your engine using `CreateMLCEngine()` with a valid model configuration.
    at MLCEngine.<anonymous> (chunk-ZOKLVKAW.js?v=427e5d1f:13082:15)
    at Generator.next (<anonymous>)
    at chunk-ZOKLVKAW.js?v=427e5d1f:978:67
    at new Promise (<anonymous>)
    at __awaiter (chunk-ZOKLVKAW.js?v=427e5d1f:960:10)
    at MLCEngine.chatCompletion (chunk-ZOKLVKAW.js?v=427e5d1f:13080:12)
    at Completions.create (chunk-ZOKLVKAW.js?v=427e5d1f:11815:24)
    at ChatWebLLM._streamResponseChunks (@langchain_community_chat_models_webllm.js?v=427e5d1f:102:55)
    at _streamResponseChunks.next (<anonymous>)
    at ChatWebLLM._call (@langchain_community_chat_models_webllm.js?v=427e5d1f:125:22)

```

**Comment by Neet-Nestor** [comment]
Could you please share the `ChatWebLLM` you are using? I'm not aware of this LangChain chat class.

**Comment by Neet-Nestor** [comment]
Interesting, this is the first time I heard this LangChain model. I read the page below and clearly their sample code there is incorrect.

https://v02.api.js.langchain.com/classes/langchain_community_chat_models_webllm.ChatWebLLM.html

Please refer to the README of this repo for the correct sample code. Specifically, you need to call `model.initialize(callback)` before you invoke it.

**Comment by Neet-Nestor** [comment]
Note that I notice the code in this langchain implementation is also not up-to-date so you may experience failure even with the initialize call. You can consider downgrade web-llm to an earlier version or wait for langchain to update it.

**Comment by Neet-Nestor** [comment]
Langchain `ChatWebLLM` has been updated to match and lock version v0.2.46. The document has also been updated.
