### ISSUE TITLE
"Only one of context_window_size and sliding_window_size can be positive"

### ISSUE THREAD

**Issue by flatsiedatsie** [mlc-ai/web-llm#478]
For Mistral 7B (I think), which one should I set to -1?

<img width="449" alt="Screenshot 2024-06-15 at 20 05 34" src="https://github.com/mlc-ai/web-llm/assets/805405/b0f2868f-2563-418e-a12e-ae3bd46b7c9e">

**Comment by CharlieFRuan** [comment]
You can set `context_window_size` to `-1` if you'd like to use sliding window, `sliding_window_size` to -1 otherwise. The official usage is without sliding window size according to Mistralv0.3's HF. This error should be fixed after 0.2.44 for prebuilt list.
