### ISSUE TITLE
Are old models being removed?

### ISSUE THREAD

**Issue by flatsiedatsie** [mlc-ai/web-llm#487]
After updating to the latest version of WebLLM I got an error in my project saying that `Qwen1.5-1.8B-Chat-q4f16_1-MLC` could not be found:

```
load_web_llm: caught error:  Error: Failed to load model: No URL found for model ID "Qwen1.5-1.8B-Chat-q4f16_1-MLC". Please check if the model ID is correct and included in the model_list configuration.
```

Checking in config.ts I see all references to Qwen1.5 are gone.

I have no issue with pruning older models from the project. I understand that can be necessary. But I do have some questions:
- What is the process/strategy for pruning old models? When are they concidered 'too old'? Are there some models that will have longer "support"? Could that strategy be made explicit? For example, why is an old version of Qwen removed, but (thankfully) old versions of Phi are still supported. For long-term support TinyLlama, Phi 3 and Mistral 7B would get my vote.
- Is there a way to be notified of pruning, or anticipate it without having to check config.ts with each update? Maybe a flag in the models list in config.ts that says `'deprecated':true` maybe? Then my code could check for that, and visually warn in the UI that the model will be removed soon.
- Would it perhaps be possible to create a `legacy_models.json` file where the last working versions of pruned models from config.js are moved to? Then I could merge that with the 'official' list in config.ts to keep old models alive a little bit longer?

**Comment by CharlieFRuan** [comment]
Sorry for the inconvenience and thanks for the suggestions! Qwen1.5 was removed because Qwen2 was supported. There is indeed not an explicit strategy for pruning old models, but most of the time it is when there is a direct substitute (in this case Qwen2 substituting Qwen1.5). On the other hand, Phi1.5 was not replaced by Phi2 because they excel in different categories.

We will consider a better strategy in terms of pruning the old models. Thank you!

**Comment by flatsiedatsie** [comment]
HasQwen2-0.5B-Instruct been removed? 

Each time I think "it was there.. right?" :-D

**Comment by CharlieFRuan** [comment]
Closing this issue, feel free to open new ones!
