### ISSUE TITLE
Both Chrome and Edge not work on win10

### ISSUE THREAD

**Issue by lucasjinreal** [mlc-ai/web-llm#49]
![image](https://user-images.githubusercontent.com/21303438/233363711-2ab31086-bc78-4f53-89a3-df4d1ac809f5.png)
![image](https://user-images.githubusercontent.com/21303438/233363729-f635cd21-dbfb-456c-af3d-0f70c329eb5d.png)

**Comment by Alex-YangSZ** [comment]
u should try Chrome Canary

**Comment by eatcosmos** [comment]
install https://www.google.com/chrome/canary/
and computer GPU memory must > 7G

**Comment by HappyPony** [comment]
It worked for me in that environment:
```
Device Model: Fujitsu Esprimo Q556
Processor:    Intel(R) Pentium(R) CPU G4400T @  2.90 GHz
RAM           8,00 GB 
Systemtyp     Windows 10 Pro 64-Bit-OS, x64-based Processor
GPU           Intel HD Graphics 510
Browser:      Chrome Version 113.0.5672.53 (Offizieller Build) beta (64-Bit)
```
Chrome I downloaded from here.
> You can download the latest on  https://www.google.com/chrome/beta/ for desktop or on Google Play Store on Android.

https://developer.chrome.com/blog/chrome-113-beta/

**Comment by tqchen** [comment]
latest chrome should work
