### ISSUE TITLE
How to actually use WebLLM

### ISSUE THREAD

**Issue by mirdulvultr** [mlc-ai/web-llm#493]
I am not able to understand how to even get started with it like how do get it to run everytime it has errors, if anybody can help i just need a simple chat interface where i show the demonstration that's it.

**Comment by lavilao** [comment]
go to https://chat.webllm.ai/ download a model, install the pwa, go offline, enjoy.

**Comment by lagschwein** [comment]
If I were you I would start with the Getting Started section of the README and trying to get the code snippets to work

**Comment by Neet-Nestor** [comment]
As suggested by other users, you could just go to https://chat.webllm.ai/ if you want to just use the package to chat, or you could check our [examples](https://github.com/mlc-ai/web-llm/tree/main/examples) with many code snippets to reference if you want to use WebLLM as a package for your own projects.

If you have more specific issues while trying to build your project, feel free to open new issues to ask any time.
