### ISSUE TITLE
Decentralized distributed Supercomputing AI

### ISSUE THREAD

**Issue by rugabunda** [mlc-ai/web-llm#50]
We should also integrate an option for distributed computing, like folding@home, dedicating a certain percentage of cpu/gpu power for a decentralized service, as decentralized supercomputing would significantly aid with computationally intensive AI tasks and or building language models.

**Comment by eatcosmos** [comment]
yes, with webgpu we can train llm with many many chrome on small computers,maybe need p2p and tranning tasks manager?

**Comment by HappyPony** [comment]
I like the idea of a swarm LLM ;-).
