### ISSUE TITLE
Deply llama 3 40 billion parameters model

### ISSUE THREAD

**Issue by ArpanDhot** [mlc-ai/web-llm#506]
Hi there,

I would like to know if I can compile 40 billion llama model. Is there a chance to also deply openai  speech to text model? 

Thanks

**Comment by CharlieFRuan** [comment]
Speech to text model is something we are looking into in https://github.com/mlc-ai/mlc-llm

For llama3, are you referring to the incoming 400B? Or the existing 70B

**Comment by ArpanDhot** [comment]
Hi CharlieFRuan, 

Thank you so much for getting back. I am referring to the 70B llama 3 model.

**Comment by CharlieFRuan** [comment]
The 70B model (3-bit quantized) is actually supported and hosted on our demo https://chat.webllm.ai/. However, it requires ~30GB of VRAM; I've only tested it on Macbook M3 Max 64GB. 

<img width="844" alt="image" src="https://github.com/user-attachments/assets/1e71dea7-6a92-4992-b62d-c5b1aef18a8d">

For such large models, we'd recommend checking out https://github.com/mlc-ai/mlc-llm, which supports CUDA/AMD/Metal backends.

**Comment by ArpanDhot** [comment]
Thank you so much CharlieFRuan
