### ISSUE TITLE
Request: Allow deletion of individual cached models.

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [mlc-ai/web-llm#516]
Would it be possible to allow deletion of individual cached models using the GUI?

**Comment by CharlieFRuan** [comment]
Hi! Please check this example: https://github.com/mlc-ai/web-llm/tree/main/examples/cache-usage

With these APIs, you can: delete a model's weights, a model's config, a model's WASM, or all of these for a model.

A developer can build GUI with these APIs.

**Comment by flatsiedatsie** [comment]
Whoa, I built this manually. But of course there's an API for this. Awesome.

**Comment by CharlieFRuan** [comment]
Closing this issue for now, feel free to open new ones.
