### ISSUE TITLE
Could we have builds/deploys to go with the latest improvements?

### ISSUE THREAD

**Issue by DustinBrett** [mlc-ai/web-llm#54]
If possible could https://github.com/mlc-ai/web-llm/actions/workflows/pages/pages-build-deployment be ran as I was not able to get a build going locally. Thanks!

**Comment by jinhongyii** [comment]
Thanks for you advice. We've already run the github action to update the website. Feel free to try out our latest demo.

**Comment by DustinBrett** [comment]
Got Vicuna 7B v1 running on my site and it's quite amazing. Thanks!
