### ISSUE TITLE
Mac OS  error while running canary in disable_robustness

### ISSUE THREAD

**Issue by josephtsukka** [mlc-ai/web-llm#56]
Getting this error in chat window when running canary from this command:

Init error, CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --enable-dawn-features=disable_robustness     

chat works fine when launched normally

**Comment by MasterJH5574** [comment]
Hi @josephtsukka, thanks for bringing it up! Something was wrong in our last website deployment an hour ago. It should be fixed now. We have updated the Vicuna model from v0 to v1 and you are very welcome to check it out :-)
