### ISSUE TITLE
Ability to choose where model gets downloaded?

### ISSUE THREAD

**Issue by xzuyn** [mlc-ai/web-llm#59]
My main drive has very little space left, and it seems to default to downloading there. Is it possible to have it install to a separate drive? I'm using Edge Beta.

edit: i've made a mklink for now. first made a folder on my z drive called `MsEdgeCache`, then opened an admin cmd.

```cd "C:\Users\USERNAME\AppData\Local\Microsoft\Edge Beta\User Data\Default\Service Worker\"```
```mklink /D CacheStorage "Z:\MsEdgeCache"```

**Comment by tqchen** [comment]
Thanks for the suggestion, this is controlled by browser and likely not something we can change
