### ISSUE TITLE
Issue with chrome extensions

### ISSUE THREAD

**Issue by adam91holt** [mlc-ai/web-llm#590]
When trying to run the chrome extension examples I can't seem to get around this error.

`Refused to connect to 'https://cdn-lfs-us-1.hf.co/repos/ea/90/ea90ac38f608f2fa13d505306d67e6a194ebbad90f61e9889a9435286d6034e0/6c681d791cf2d278843952540386171f96f3acd25007b688169fd4bc6a28b923?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27params_shard_26.bin%3B+filename%3D%22params_shard_26.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1728203236&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyODIwMzIzNn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLm...MDdiNjg4MTY5ZmQ0YmM2YTI4YjkyMz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomcmVzcG9uc2UtY29udGVudC10eXBlPSoifV19&Signature=AzDYlr0wmkvD8j5JGrNod0B3J3ici8QqOj5FSoLhqwuiE9ZxpnYO8Kv7Bzqgd23rCv27vx3RfEISOjfxW2hWDqWr6QSlTaWxoKRNiGD%7EGnDMIvH1ySdENFlZj17n7aas%7Ed6VriLXTQESqaS56mXHLs6tSUQ1z2VoGDMKr3WtZTrhhcj%7EPy8Uej9y%7E4l6CBZ3-6TL7wj38IL%7EF6TMnu7CTweWHAEVoWzsY0kBBtK1Y%7E0colESvRXaOFEf32%7EsZsGHXzYOKHNiSxffcUuRB%7E1Ow-SfdHHOOkuJqV%7ExN8tKMFEoTB5WklN59KwabZs0crWh8dUNhyNNaLLedrCfBJJ%7EOw__&Key-Pair-Id=K24J24Z295AEI9' because it violates the following Content Security Policy directive: "connect-src 'self' data: http://localhost:8000 https://huggingface.co https://cdn-lfs.huggingface.co https://cdn-lfs-us-1.huggingface.co https://raw.githubusercontent.com".`

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/05d83e7e-3ee5-45e5-bafb-bca10d255a12">

Any ideas?

**Comment by CharanSriramUni** [comment]
Looks like the domain huggingface uses for caching weights was changed; I added `https://cdn-lfs-us-1.hf.co` to the manifest and it seemed to get past this issue.

That said, I am still having trouble running the service worker extension example. I'm currently getting the following error:
```Error in event handler: Error: return from a unknown uuid, msg=[object Object]``` and the model doesn't seem to get loaded.

**Comment by Neet-Nestor** [comment]
> When trying to run the chrome extension examples I can't seem to get around this error.
> Any ideas?

As @CharanSriramUni mentioned above, this is due to the new huggingface domain name not being included in the example extension's CSP configuration. https://github.com/mlc-ai/web-llm/pull/603 should resolve this.

**Comment by Neet-Nestor** [comment]
> Looks like the domain huggingface uses for caching weights was changed; I added `https://cdn-lfs-us-1.hf.co` to the manifest and it seemed to get past this issue.
> 
> That said, I am still having trouble running the service worker extension example. I'm currently getting the following error: `Error in event handler: Error: return from a unknown uuid, msg=[object Object]` and the model doesn't seem to get loaded.

This error is fine. It happens when the popup receives message that was not sent by it from the service worker.

I have tried the service worker extension example by myself and it works fine on my end. Could you please try again and let me know if the issue persists?

**Comment by CharanSriramUni** [comment]
Oh. Seems to work now. I think there might be an issue if the extension popup is clicked several times while loading but the Qwen model loads and works for me if allowed to load.

**Comment by darshjme-codes** [comment]
This CSP violation is happening because the Hugging Face CDN URL includes query parameters that aren't whitelisted in your extension's manifest.

**Root cause:** The CSP policy in your `manifest.json` only allows specific HF domains, but the `cdn-lfs-us-1.hf.co` endpoint with dynamic query params is being blocked.

**Fix: Update manifest.json CSP**

```json
{
  "content_security_policy": {
    "extension_pages": "script-src 'self'; object-src 'self'; connect-src 'self' data: http://localhost:8000 https://huggingface.co https://*.huggingface.co https://*.hf.co https://raw.githubusercontent.com;"
  }
}
```

**Key changes:**
- Added `https://*.hf.co` to allow all HF CDN subdomains
- This covers `cdn-lfs-us-1.hf.co`, `cdn-lfs.hf.co`, etc.

**Alternative (if using Manifest V2):**
```json
{
  "content_security_policy": "script-src 'self'; object-src 'self'; connect-src 'self' data: http://localhost:8000 https://huggingface.co https://*.huggingface.co https://*.hf.co https://raw.githubusercontent.com;"
}
```

**After updating:**
1. Reload the extension in `chrome://extensions/`
2. Hard refresh the page (Ctrl+Shift+R)

Let me know if you're still seeing the error! 🔧
