### ISSUE TITLE
Better NavBar and Footer can be implemented

### ISSUE THREAD

**Issue by NishantRana07** [mlc-ai/web-llm#599]
NavBar needs some changes and some addition linked like About us and Contact Us

Footer can be added with socials 

Please Assign it to me under hacktoberfest and GSSoc  for Better convenience and faster execution

**Comment by naaa760** [comment]
Hello @NishantRana07 
I would like to work on this issue, please assign me.

**Comment by NishantRana07** [comment]
@davidpissarra @nicolas-raoul If you need to implement it, Please Assign it to me else you can close this comment

**Comment by Neet-Nestor** [comment]
Closed as duplicate issue https://github.com/mlc-ai/web-llm/issues/605 , please move any related discussion there.
