### ISSUE TITLE
'LlamaConfig' object has no attribute 'max_sequence_length'

### ISSUE THREAD

**Issue by davidar** [mlc-ai/web-llm#61]
I followed the instructions for converting LLaMA/vicuna weights, but it seems it didn't put a `max_sequence_length` property into `config.json` (https://github.com/huggingface/transformers/issues/22433#issuecomment-1489436694) and hence when running `build.py` I got an error on https://github.com/mlc-ai/web-llm/blob/28332cb0f3eeb2baa693f8df60ba3eb7216bbba5/web_llm/utils.py#L13

Commenting out this line seems to fix it.

**Comment by jinhongyii** [comment]
Good Catch! We didn't consider the case where user use scripts to convert llama weights, and that's indeed a bug. Can you create a PR for the fix by just commenting out that line? Thank you.
