### ISSUE TITLE
[embeddings] Any plans for adding other transformer models like sentence-transformers?

### ISSUE THREAD

**Issue by jlia0** [mlc-ai/web-llm#67]
Would be really nice to have WebGPU support for running other transformer models like sbert and embeddings models. For example, here's [transformer.js](https://xenova.github.io/transformers.js/)

Thanks!

@jinhongyii

**Comment by jinhongyii** [comment]
Thank you for advice. We are happy to see more and more model support in web-llm. There are already open PR about ChatGLM and Dolly model support. If you are interested in bringing embedding models in, you can take them as a reference and bring up new PR.

**Comment by jlia0** [comment]
Are there any specific modifications needed for embeddings models? For example, does the TensorIR technique still apply to embeddings models?

**Comment by jinhongyii** [comment]
Yes of course embedding can be represented in TensorIR. So basically what you need is to translate the model (pytorch implementation) into corresponding relax operator. If there's no direct translation, write TensorIR manually or write te expressions that can be converted to TensorIR

**Comment by CharlieFRuan** [comment]
Hi, npm 0.2.60 has initial support for embedding and RAG, check out usage here: https://github.com/mlc-ai/web-llm/tree/main/examples/embeddings

Currently only [snowflake-arctic-embedding](https://huggingface.co/Snowflake/snowflake-arctic-embed-m) is supported.

Closing for now, feel free to open new issues.
