### ISSUE TITLE
Run Web LLM on a Linux on Android?

### ISSUE THREAD

**Issue by HappyPony** [mlc-ai/web-llm#70]
Hi,

Linux can be installed and run on Android smartphones. For example, I have Ubuntu Version 20.04.3 LTS (Focal Fossa) and Debian version_ID=10 (buster) - with certain restrictions under the UserLand app https://userland.tech/. 

Could it be a promising approach to try to run Web-LLM on such a Linux instance?

**Comment by jinhongyii** [comment]
I'm not sure about this. You can have a try

**Comment by tqchen** [comment]
checkout android examples at https://mlc.ai/mlc-llm/docs/
