### ISSUE TITLE
Where stores Web LLM initial weights

### ISSUE THREAD

**Issue by HappyPony** [mlc-ai/web-llm#73]
Where stores Web LLM initial weights on a Windows PC? It is
> C:\Users\UserName\AppData\Local\Google\Chrome Beta\User Data\Default\Service Worker\CacheStorage 

correct? This folder occupies 4.5 GB for me.
Windows 10 Pro, version 22H2

**Comment by tqchen** [comment]
this is likely browser dependent, but in your case that looks like the right folder

**Comment by HappyPony** [comment]
What is the path to the Web LLM initial weights folder in your browser @tqchen  :-) ?

**Comment by tqchen** [comment]
I don't know :) never looked it up
