### ISSUE TITLE
Chat demo is not working in Chrome 113.

### ISSUE THREAD

**Issue by lcw99** [mlc-ai/web-llm#78]
I got following errors on your demo page.

```
Find an error initializing the WebGPU device Error: Cannot find adapter that matches the request
Init error, Error: Find an error initializing WebGPU: Error: Cannot find adapter that matches the request
```

**Comment by deepkolos** [comment]
needs chrome beta 113+
1. try open chrome://flags
2. search webgpu then enable it

**Comment by lcw99** [comment]
![image](https://user-images.githubusercontent.com/30032204/236576216-7f68cdc9-7aba-451f-9cd8-cb7d27dd08d3.png)

I've tried chrome beta 114.0.5735.16 with webgpu enabled, but got same error. Ubuntu 20.04.

**Comment by deepkolos** [comment]
@lcw99  try this to check webgpu support status 

https://webgpureport.org/

**Comment by lcw99** [comment]
![image](https://user-images.githubusercontent.com/30032204/236655170-f6aadafa-f8fe-4675-a90d-b71e05cc5b85.png)

**Comment by gsmlg** [comment]
Same issue because no physical GPU

**Comment by Erudition** [comment]
> ![image](https://user-images.githubusercontent.com/30032204/236576216-7f68cdc9-7aba-451f-9cd8-cb7d27dd08d3.png)
> 
> I've tried chrome beta 114.0.5735.16 with webgpu enabled, but got same error. Ubuntu 20.04.

It's not just  WebGPU Developer features, but the unsafe WebGPU flag as well, no?

**Comment by codingjlu** [comment]
I've tried using Chrome Dev (115) and enabled WebGPU, still getting the exact same error. I've tried webgpureport.org and everything's working fine...

**Comment by knoopx** [comment]
needed to run with `google-chrome-stable --enable-unsafe-webgpu`, the chrome://flags alone did not work

**Comment by knoopx** [comment]
@codingjlu just a warning that webgpu is experimental and unsafe and that you are at your own risk

**Comment by tqchen** [comment]
Closing for now, likely latest chrome canary can work
