### ISSUE TITLE
Reset chat isn't working

### ISSUE THREAD

**Issue by DustinBrett** [mlc-ai/web-llm#83]
For me WebLLM's Reset did not work if you tried to chat after a reset. I tracked it down to `#clearKVCache` requiring `this.kvCacheLength = 0` at the end. But I am not sure if this fix is ideal so I figured I would post it here to see if others had issues with Reset.

**Comment by tqchen** [comment]
Great point, please send a PR to fix it. This is indeed a miss that we overlooked

**Comment by DustinBrett** [comment]
Merged fix so I can close this for now.
