### ISSUE TITLE
Hi, I made a new website for web-llm!

### ISSUE THREAD

**Issue by Ryan-yang125** [mlc-ai/web-llm#88]
Hi there! 

I want to share that I've been enjoying using web-llm and its demo for some time now. However, I found that the demo didn't quite meet my needs for more in-depth usage. As a result, I decided to create a new app based on web-llm, which now functions as a fully-realized chat app!

## Here is my project [ChatLLM-Web](https://github.com/Ryan-yang125/ChatLLM-Web)  , which supports:
- ⚙️ Model runs in a web worker, ensuring that it doesn't block the user interface and providing a seamless experience.
- 🚀 Easy to deploy for free with one-click on Vercel in under 1 minute, then you get your own ChatLLM Web.
- 💬 Multi-conversation chat, with all data stored locally in the browser for privacy.
- 📝 Markdown and streaming response support: math, code highlighting, etc.
- 🎨 responsive and well-designed UI, including dark mode.

## Here is a screenshot of it: 
![cover](https://user-images.githubusercontent.com/53991079/236999190-37531693-22dd-4da4-b9ef-c589829b01e7.png)

Hope this will help web-llm 😊！

**Comment by Ryan-yang125** [comment]
Also, I would like to express my gratitude to @DustinBrett! 
I was able to reference your initial [commit](https://github.com/DustinBrett/daedalOS/commit/9b93cd96b9a878ce5fbe7f048663b4da5e5fb90a) to load web-llm in a web worker and reimplement it for my own project. 
Your work on [daedalOS](https://github.com/DustinBrett/daedalOS) is truly impressive, and I must say it's the most remarkable desktop environment I've ever seen in a browser. Keep up the great work!

**Comment by DustinBrett** [comment]
> Also, I would like to express my gratitude to @DustinBrett! I was able to reference your initial [commit](https://github.com/DustinBrett/daedalOS/commit/9b93cd96b9a878ce5fbe7f048663b4da5e5fb90a) to load web-llm in a web worker and reimplement it for my own project. Your work on [daedalOS](https://github.com/DustinBrett/daedalOS) is truly impressive, and I must say it's the most remarkable desktop environment I've ever seen in a browser. Keep up the great work!

Thanks very much @Ryan-yang125! Your project looks very cool, I may have to get some inspiration for my AI Chat program from it, especially for things like the markdown formatting as mine is currently quite basic. WebLLM is an amazing project and it's exciting integrating it into our projects. I'd still like to add so many things such as STT/TTS and an entire AI assistant for my desktop environment similar to Cortana but hopefully smarter and more useful. I could see this being quite powerful as we start to get better models, although Vicuna 7B is already rather impressive. Good luck!
