### ISSUE TITLE
Please release a prebuilt copy

### ISSUE THREAD

**Issue by qwertie** [mlc-ai/web-llm#95]
I bet a lot of people would find it fun to run an LLM locally without the need for internet access. Could you provide a prebuilt Wasm copy (with a README)?

IIUC, when this project is built, it is essentially a static web site that can be served by any static file server. A prebuilt version would require only one tool to be installed (the file server), whereas building from scratch requires installing python, pip3, emscripten, git, a C++ compiler (I think? It was only implied), Rust, wasm-pack, Ruby and Jekyll. (Of course, Chrome Canary and a model are also needed either way.)

**Comment by tqchen** [comment]
Thank your for your suggestion, WebLLM is now part of npm, checkout latest examples in https://github.com/mlc-ai/web-llm#get-started
